### ISSUE TITLE
Validate CSV-W metadata against QB/SKOS/DCAT without converting to RDF

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#10]
Validate the QB/SKOS/DCAT metadata from the CSV-W without converting to RDF

Should be fine to write this tool in python since the number of triples is pretty small here.

- [ ] Action: determine which of the constraints can be validated outside of SPARQL, decide which of these is in scope.
- [ ] Some kind of user journey?
- [ ] Could we run csvlint at the end? Is that too similar to what we have now (i.e., can be prone to error?)

**Comment by robons** [comment]
Superceded by SHACL constraints work in Application Profile.
