### ISSUE TITLE
Validate CSV-W observations against QB/SKOS/DCAT without converting to RDF

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#11]
# Validate the observations according to the QB/SKOS/DCAT specs
Will be run over all of the data in the CSV file so is python performant enough to run these checks? Should we have another tool in Scala?

Implementing the DCAT tests should be easy - we can simply lift the SPARQL queries we already have and run them in a python script against the JSON-LD CSV-W metadata document.

The SKOS & QB constraints might be a bit more difficult and will involve looking at the values defined inside the CSV itself (as well as looking at the metadata). So some of the tests can probably be brought over as SPARQL tests, but others will need to be re-written in python to go look at the CSV values.

**Comment by robons** [comment]
Will hopefully be implemented as part of the Application Profile work.
