### ISSUE TITLE
Identify which SPARQL tests can be reused against JSON-LD

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#143]
- [ ] Discover the SPARQL tests which will work immedately against JSON-LD
- [ ] Figure out which SPARQL tests could be rewritten to work in a combination of SPARQL against the JSON-LD + python/pandas code looking at the CSV's data.

At the moment we will not be able to pull in any dependencies (e.g. externall defined dimension properties, etc.) but we will hopefully be able to do this in the future.

- [ ] Try and keep a list of queries which we could run locally once we've done the dependency definition work properly (so we can pull in those externally defined resources).

**Comment by canwaf** [comment]
Related #421

**Comment by robons** [comment]
I've had a review of the code now. I'm not sure we should be merging it in to the main branch but we should certainly keep it available to look at as we decide where to go from here.

**Comment by mikeAdamss** [comment]
oh god no, not a merge, its messy, just wanted to put ideas somewhere
