### ISSUE TITLE
Trial with individuals

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#162]
We need to start trialling the process with colleagues on a one-to-one basis surveying roles and experience.

I suspect we probably need the Jenkins pipeline work to be completed (Issue #26) before people will *really* be able to give the tool a go and see that they gets the outputs they expect to get (or they have to go back and fix their info.json/CSV structure and have questions/concerns about the new syntax).

@mikeAdamss, @RedWalters, @Shannon95, @osamede20:

We would like to support you through the process of converting existing transformations from using the cubes approach to using the csvwlib approach to generating CSV-Ws.

We think it'd work best if you pair up and we'll assign one of our team to help support you through the process. Could you organise amongst yourselves and let us know your availability. Some time during the next sprint would be good.

**Comment by canwaf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-utils-60d4aba8ecae03000e18503d/issues/GSS-Cogs/csvwlib/162?planning-poker) with ZenHub @robons @santhosh-thangavel
