### ISSUE TITLE
Full-team demonstration/walkthrough

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#163]
Following on from the discussions in #162 and the presentation in #160, we need to present the basically finished internal product to the users who're going to be using it.

We might be able to re-use the presentation (with some changes) from #160.

**Comment by canwaf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-utils-60d4aba8ecae03000e18503d/issues/GSS-Cogs/csvwlib/163?planning-poker) with ZenHub @robons @santhosh-thangavel
