### ISSUE TITLE
Upgrade to rdflib 6.0.*

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#177]
We're currently using rdflib 5.0.0 due to the fact that there are some breaking changes holding us back from using 6.0.*. 

When this happens, we should remove the use of rdflib-jsonld from anywhere that uses it (including csvqb & pmd). [rdflib itself how has functionality for (de-)serialising JSON-LD](https://github.com/RDFLib/rdflib-jsonld/tree/0.6.2#archived). 

Investigate the types of breaking changes implemented, the things we need to fix, and how to fix each type of thing.

Make sure that the solutions are portable so that `gss-utils` can adopt this approach to migrating from `rdflib~=5`.

Create sub-issues for this epic following the initial spike.

**Comment by canwaf** [comment]
The pydantic incantation is `pydantic --lib .`

**Comment by canwaf** [comment]
This still doesn't work. Pydantic is expecting `from rdflib.namespace._VOID import VOID`, which we shouldn't have to do. I suppose the upgrade is going to be easy (it was incredibly light touch); however until either pydantic behaves or rdflib fixes this we should hold off.

Additionally, gss-utils is absolutely not ready for this, so I suggest we close.

**Comment by robons** [comment]
Here's a PR where I've upgraded everything to rdflib 6.0.x and removed all references to rdflib-jsonld. I've managed to get the build passing. We *should* be able to downgrade to package constraint to `rdflib>=5.0.0` and if we re-install rdflib-jsonld then we'll have something that *should* world with both rdflib 5.0.0 and 6.0.x.
