### ISSUE TITLE
Supplement gss-utils csvwlib-integration documentation

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#184]
In the `AttributeColumns.md` part of documentation, for *existing* attribute with *new* values, include the scenario where the datamaker values have “Provisional”, “Final” as existing with a new value of “Revised”.

To be clear: Existing attributes can have *new attribute values* defined against them, but the documentation doesn't inform anyone how they would go about doing that.

**Comment by robons** [comment]
We're deprecating the use of gss-utils in future transformation work.
