### ISSUE TITLE
Ensure compatibility with python 3.10

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#195]
Python 3.10 [has recently been released](https://pythoninsider.blogspot.com/2021/10/python-3100-is-available.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+PythonInsider+%28Python+Insider%29) but causes some problems with our code. Unit tests are failing. We need to find out what's failing, how much of our code needs rewriting/fixing and whether that will impact on our ability to support python 3.9. 

To make it clear: we want to be able to support *both* Python 3.9 and 3.10, so let's not start using any 3.10-specific features if we can avoid it. We might need to do some if statements/branching depending on the version of python that the tool is being run under. e.g.

```python
if 3.9:
  do_thing()
elif 3.10:
  do_other_thing()
```

Ideally, we could set up multiple docker files for 3.9/3.10 so we can test that all tests pass in both containers before publishing. This doesn't necessarily have to be part of the standard Jenkins build, but could be part of a special build process we do when releasing. We're likely to want to extend this when 3.11, etc. are released in future.

If there is little work to do, do it as part of this task, else convert this into an epic with appropriate sub-tasks.

**Comment by CharlesRendle** [comment]
TDL:

- [ ] Get BDD tests working through tox - think this is because the command needs to be executed from the .feature files location

- [ ] Unit tests are not working in the csvcubed package `ModuleNotFoundError: No module named 'csvcubedmodels'`

- [ ] Apply these changes to all subsequent packages (csvcubed-models, e.c.t)

- [ ] Write script to run the tox command for all packages (run x3)

- [ ] Github action to trigger this script

**Comment by CharlesRendle** [comment]
Jenkins file/ tox stage now starts the container from `pythonversiontesting` directory successfully but the subsequent tox commands are not recognised. Jenkins returns `tox: not found`

**Comment by robons** [comment]
@CharlesRendle: pydantic have just released v1.9.0 which has python 3.10 support - I've released an updated csvcubed-version of the project with our bug fixes on top. Upgrading the version of csvcubed-pydantic in the csvcubed project should stop the errors you were seeing coming from pydantic when using python 3.10.

https://pypi.org/project/csvcubed-pydantic/1.9.0/
