### ISSUE TITLE
Split out packages and devcontainers into separate repositories

### ISSUE THREAD

**Issue by roblinksdata** [GSS-Cogs/csvcubed#205]
All of our packages are currently contained in a single csvwlib repository to make mutual development easier. 

We have had to do some unpleasant hacky things to ensure we can still install the packages in other projects which we will now be able to undo:
- We can stop referencing `sharedmodels` as a dev dependency in `csvqb` and `pmd` packages.
- This means we can also stop having to manually install `sharedmodels` when installing `csvqb` or the `pmd` packages - it should be installed as a dependency of these packages.
- We can have one dev container per project which has the poetry dependencies installed at the global level instead of having to enter into different poetry environments for each project.

-
-

- [x]  Investigate and come up with a plan on how we can have a dockerfile per repo (and thus a .devcontainer per repo). And make sure each repo has all the dependencies it needs in the toml files.
- [x]  Sit down with you and Andrew to identify what elements of the proposed plan we need to prove due to any uncertainties. I will set up a meeting for wider #cogs_features channel.
- [x] Create tickets related to the implementation of plan.

**Comment by canwaf** [comment]
Target: Recommendation, discussion, then implementation

**Comment by canwaf** [comment]
Decision: go with splitting modules, not using git-submodules.
