### ISSUE TITLE
Unique values - case sensitivity problem

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#212]
The following test fails with the following error...

```python
import pytest
import pandas as pd

from csvqb.utils.qb.standardise import convert_data_values_to_uri_safe_values
from csvqb.models.cube import *


def test_something():
    obs = pd.DataFrame({
        "Some Dimension": ["a", "b", "A"],
        "Value": [1, 2, 3]
    })
    cube = Cube(
        CatalogMetadata("Some Cube"),
        obs,
        [
            QbColumn("Some Dimension", NewQbDimension.from_data("Some Dimension", obs["Some Dimension"])),
            QbColumn("Value",
                     QbSingleMeasureObservationValue(measure=NewQbMeasure("Some Measure"), unit=NewQbUnit("Some Unit"))
                     )
        ]
    )
    convert_data_values_to_uri_safe_values(cube)


if __name__ == "__main__":
    pytest.main()
```

```bash
  File "/usr/local/lib/python3.9/site-packages/csvqb/writers/qbwriter.py", line 56, in write
    convert_data_values_to_uri_safe_values(
  File "/usr/local/lib/python3.9/site-packages/csvqb/utils/qb/standardise.py", line 98, in convert_data_values_to_uri_safe_values
    _overwrite_labels_for_columns(
  File "/usr/local/lib/python3.9/site-packages/csvqb/utils/qb/standardise.py", line 156, in _overwrite_labels_for_columns
    column_values.categories = new_category_labels
  File "/usr/local/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 732, in categories
    new_dtype = CategoricalDtype(categories, ordered=self.ordered)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/dtypes/dtypes.py", line 183, in __init__
    self._finalize(categories, ordered, fastpath=False)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/dtypes/dtypes.py", line 337, in _finalize
    categories = self.validate_categories(categories, fastpath=fastpath)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/dtypes/dtypes.py", line 540, in validate_categories
    raise ValueError("Categorical categories must be unique")
ValueError: Categorical categories must be unique
```

This error occurs because the values "a" and "A" are treated as separate categories/code-list concepts due to one being lower case and the other being upper case. These get pathified to the same lower-case value `a` which causes our categorical standardisation function to fall over since pandas is handed a list with duplicate categories in it.

- [ ] All `from_data` methods should ignore case when finding unique values - we don't want to create duplicate resources
- [ ] The standardisation function should standardise the case of all values before converting the pandas column to categorical - this should help avoid the actual error we saw.
- [ ] You also need to add some documentation *somewhere* that makes it clear that *by default* the codes are matched in a case-insensitive fashion.

**N.B. Needs discussion: do we want some option to override this functionality? What should we do where dimension values are case-sensitive (e.g. identifiers which are distinguishable based on case)? We would presumably have to avoid pathifying values too.**

**Comment by canwaf** [comment]
Can we assume capitalisation cannot be unique? Or should this be a switch? I ask because it's a very western/Latin approach.

**Comment by robons** [comment]
> Can we assume capitalisation cannot be unique? Or should this be a switch? I ask because it's a very western/Latin approach.

I think it should be a switch. Someone is bound to come along with case-sensitive identifiers at some point and complain.

**Comment by robons** [comment]
@canwaf we've also discovered datasets which happen to achieve this problem where lower-casing everything isn't a solution. e.g. `This is an identifier` and `This  is an identifier` look like unique values but evaluate to the same pathified identifier `this-is-an-identifier` (note the double space in the second string).

It would be useful if whilst you're doing this work, you could implement a validation check which looks for problems like these and highlights the conflicting identifiers which need correcting.

**Comment by canwaf** [comment]
Okay. So my though is that if there are different values which resolve to the same pathified string, we throw a warning but proceed with the pathification? Thoughts, @robons?

**Comment by robons** [comment]
Unfortunately that'll cause pandas to throw the exception. I think we should look for conflicts in the validation process (i.e. before the serialisation functionality is even evaluated). 

But we should still ensure that we solve the case-sensitivity problem since that'll be the most common conflict we have and is relatively easy for us to fix for them. I don't think we can reasonably fix more complex conflicts, so an exception where they try to force us down that road is a sensible approach.
