### ISSUE TITLE
Standardised URIs

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#22]
Having a template for each uri coined. @rossbowen to work with @ajtucker for an opinionated document for this.

* Local
* Family
* Global

And all of the QB resources (components, properties, dsd, etc.)

**Comment by rossbowen** [comment]
WIP.

To review:
- https://www.w3.org/wiki/HashVsSlash
- http://ukgovld.github.io/ukgovldwg/recommendations/uri-patterns.html
- https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/60975/designing-URI-sets-uk-public-sector.pdf

|                           |               |                                                                                         |
|---------------------------|---------------|-----------------------------------------------------------------------------------------|
| Data Cube                 |               | `gss-data.org.uk/data/{dataset-name}`                                                   |
| Data Structure Definition |               | `gss-data.org.uk/data/{dataset-name}/structure`                                         |
| Component                 |               | `gss-data.org.uk/data/{dataset-name}/component/{component-name}`                        |
| Dimension                 | Global        | `gss-data.org.uk/def/dimension/{dimension-name}`                                        |
| Dimension                 | Within-family | `gss-data.org.uk/def/{family-name}/dimension/{dimension-name}`                          |
| Dimension                 | Local         | `gss-data.org.uk/data/{dataset-name}/dimension/{dimension-name}`                        |
| Measure                   | Global        | `gss-data.org.uk/def/measure/{measure-name}`                                            |
| Measure                   | Within-family | `gss-data.org.uk/def/{family-name}/measure/{measure-name}`                              |
| Measure                   | Local         | `gss-data.org.uk/data/{dataset-name}/measure/{measure-name}`                            |
| Attribute                 | Global        | `gss-data.org.uk/def/attribute/{attribute-name}`                                        |
| Attribute                 | Within-family | `gss-data.org.uk/def/{family-name}/attribute/{attribute-name}`                          |
| Attribute                 | Local         | `gss-data.org.uk/data/{dataset-name}/attribute/{attribute-name}`                        |
| Codelist                  | Global        | `gss-data.org.uk/def/codelist/{codelist-name}`                                          |
| Codelist                  | Within-family | `gss-data.org.uk/def/{family-name}/codelist/{codelist-name}`                            |
| Codelist                  | Local         | `gss-data.org.uk/data/{dataset-name}/codelist/{codelist-name}`                          |
| Concept                   | Global        | `gss-data.org.uk/def/codelist/{codelist-name}/concept/{concept-name}`                   |
| Concept                   | Within-family | `gss-data.org.uk/def/{family-name}/codelist/{codelist-name}/concept/{concept-name}`     |
| Concept                   | Local         | `gss-data.org.uk/data/{dataset-name}/codelist/{codelist-name}/concept/{concept-name}`   |
| Observation               |               | `gss-data.org.uk/data/{dataset-name}/obs/{concept-1}/{concept-2}/.../{concept-n}` |

**Comment by rossbowen** [comment]
Will likely want API work to progress further before implementing any change here. `csvwlib` is progressing on the basis of the previous URI schemes.

Will move to icebox to revisit at a later date.

**Comment by ajtucker** [comment]
Also need to consider putting family and common/global identifiers under reference.data.gov.uk and how we can fit with what's already there.

**Comment by canwaf** [comment]
For the purposes of csvwlib is a "family"-level components accurate and suitably descriptive? Our use of family descriptors might be confusing to people using our dataset. We've got contained (i.e. in Qube) components, externally controlled components (i.e. reference.data.gov.uk), and this third one where the publisher/user is assumed to know what they're doing.

Do we want to surface functionality to generate this third type of standardised URIs in csvwlib? I know we need this internally, but I don't think that we should make this apart of the public API.

**Comment by rossbowen** [comment]
I dislike the notion of `family` being used for anything other than an internal ONS identifier to coincide with projects we're undertaking. I prefer the idea of theme-level URIs.

> third one where the publisher/user is assumed to know what they're doing.

I would like to be able to say to a department like BEIS or DfE that they should do some discovery on the sorts of dimensions/measures they're reporting on, and then to advise them to coin some theme level uris like `http://data.gov.uk/climate/dimension/greenhouse-gas` for reuse across their publications. Essentially teaching them to manage an ontology of components

Atm we do this outside of the `info.json` using CSV files containing data about these components [e.g. here](https://github.com/GSS-Cogs/family-climate-change/blob/master/reference/properties.csv). I don't know whether we would essentially ask departments to do the same.

**Comment by canwaf** [comment]
I think that coining these "common" dimensions should be treated as a special service for government departments provided by us, and that effectively they should be treated as global. Eventually we could allow the departments to maintain the codelists themselves, but certainly not at first.

**Comment by ajtucker** [comment]
Whatever we call the dimensions and codelists that are used by more than one dataset, we do need to have some hierarchy and a way to group these things together, so need to decide on URI components that reflect the hierarchical grouping.

Normally with URIs, we'd use the publishing organisation's DNS name as the top level of this hierarchy, but as we're expecting these particular dimensions and codelists to be shared and not necessarily owned or managed by a single organisation, but rather by a consortium of concerned orgs, we're proposing some top-levels of the hierarchy to reflect these groups/consortia.

The term "family" has been defined as "a group of datasets that share common dimensions & codelists", so seems to fit quite well with this top level of the hierarchy, but we could equally use another term with a similar definition to reflect more the notion that it should be a shared responsibility to manage the dimensions & codelists under that grouping.

If we're to use reference.data.gov.uk, we need some top level paths that don't clash with the existing time period paths (year, month, etc.).
