### ISSUE TITLE
Bug Reporting - User Guidance

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#229]
This is about documenting *how* the user goes and submits some kind of bug report and/or gets support from the IDP-D team.

Need to think about the template we want for creating github issues. (Make sure to say to include the debug log, etc.)

Make sure that when you submit a new issue, you automatically see the issue populated with our guidance template.

N.B. Make sure the user knows how to include detailed error logging as described in Issue #60. (Attach error log file to the issue).

+ Also make sure we provide information on how to email sensitive bug reports too us (probably in our written docs) - and make sure it's clear we have the same information as in the github bug report.

**Comment by robons** [comment]
@MuazzamChaud this might be a good one for you.

**Comment by robons** [comment]
csvcubed@gsscogs.uk - where you can email sensitive issues to.

**Comment by CharlesRendle** [comment]
Have opened a [draft PR](https://github.com/GSS-Cogs/csvcubed/pull/372)

I think the issue with my YAML template is syntactical. I also need to verify the output of submitting an issue through a github form (will it produce a simple ticket).
