### ISSUE TITLE
rdflib 6.0 Conversion

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#235]
From Spike #221 

1. In `csvcubed-models/csvcubedmodels/rdf/dcat.py`, `DCTERMS.title` now present in rdflib 6
```python
- title: Ann[str, Triple(DCTERMS.term("title"), PropertyStatus.recommended, map_str_to_en_literal)]
+ title: Ann[str, Triple(DCTERMS.title, PropertyStatus.recommended, map_str_to_en_literal)]
```

2. Upgrade pyprojects.toml (e.g. `csvcubed-models/pyproject.toml`)
```python
- rdflib = "⋍5.0.0"
+ rdflib = ">6.0"
```

That's it for csvcubed. Though pydantic validation currently fails due to issues surrounding `from rdflib.namespace import FOAF` when it expects `from rdflib.namespace._FOAF import FOAF`, which obviously isn't by design for either of them. Will continue to watch.

**Comment by robons** [comment]
This issue has already been addressed. We are currently using rdflib >= 6.0.0.
