### ISSUE TITLE
"Climate Change" family breaks infojson2csvqb

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#237]
This problem affects gss-utils, however the problem may be best fixed in the csvcubed package/project.

If you set the families in an info.json to the below and pass it to the `infojson2csvqb` command then you achieve an error:

```json
"families": [
  "Climate Change"
],
```

```bash
$ infojson2csvqb build -c info.json observations.csv 
CSV: /workspace/datasets/ONS-UK-Total-trade/observations.csv
info.json: /workspace/datasets/ONS-UK-Total-trade/info.json
http://gss-data.org.uk/def/gdp#Climate Change does not look like a valid URI, trying to serialize this will break.
http://gss-data.org.uk/def/gdp#Climate Change does not look like a valid URI, trying to serialize this will break.
Build Complete
```

We need to examine how gss-util approaches this and do the same thing in the csvcubed approach.

**Comment by canwaf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-utils-60d4aba8ecae03000e18503d/issues/GSS-Cogs/csvcubed/237?planning-poker) with ZenHub @robons @anojperera @MartynBSpooner @MuazzamChaud

**Comment by canwaf** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-utils-60d4aba8ecae03000e18503d/issues/GSS-Cogs/csvcubed/237?planning-poker) with ZenHub @calum-fairchild-methods
