### ISSUE TITLE
Info.json v2.0 json schema

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#239]
We need to come up with a new info.json v2 structure which holds the information necessary to generate a CSV-W by an external data producer. We need to make it as straight forward as possible but it should capture *all* of the metadata we need.

- [x] Metadata to go into DCAT 
  - [ ] simple sourcing information - where the data can be found from in an alternative format/source.
- [x] Column mappings to define the qb:DSD
   - [ ] How do we define code-lists against dimensions? Do we want to?
- [x] Can we support a more natural input shape for multi-measure datasets? i.e. multiple measure-observations per input row instead of requiring a `Measures` column to be created?

Come up with a proposed structure, present it in a desgin session to the wider team, take feedback on board and reiterate until we're happy with the issue.

**Comment by robons** [comment]
Just throwing this stuff here so we don't forget about it (I can't remember where it came from tbh):

* We need to create a flow chart to help users decide how they decide what goes into their JSON config file.
  * e.g. Go through each of your columns and add it into the mapping section of the JSON file.
  * For each column, decide whether it's a dimension/attribute/observed value/measure/unit - provide helpful info here to help them figure this process out - a series of questions they can ask themselves to figure it out.
* How and where do users add footnotes/comments to dimensions/code-lists/concepts in code-lists/attributes/attribute-values/etc.?
