### ISSUE TITLE
Case-sensitivity as a feature (not a bug)

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#250]
Due to the bug #212, it was decided that since the primary use cases of csvcubed would involve case-insensitive destinations, data would be modified when two different values would coalesce into a single uri_safe value (i.e. patified to use dashes instead of spaces, be lower case, etc.).

The user should be able to choose to use case-sensitive outputs and preserve case-sensitivity across the CSV-W generation process. This would have upstream implications in converting to RDF. It's not an easy problem to solve.

The method which implements this is `csvcubed.utils.qb.standardise.standardise_categoricals()`, this would need to be unpicked and new tests other than `tests.unit.cube.qb.test_cubeqb_errorvalidation/test_case_insensitivity_code_collisions()` would need to be written.

**Comment by robons** [comment]
We're no longer standardising catagoricals due to us not wanting to incorrectly interpret what a user has provided.
