### ISSUE TITLE
Create Glossary Documentation Page

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#259]
There are a number of key terms we're likely to use in our documentation that may be difficult for users to understand. We should provide a glossary page where users can go to quickly look up what a term means.

Terms which immediately come to mind include:

* dimension
* observation (value)
* attribute
* measure
* population characteristic
* unit
* tidy data
* URI
* aggregate
* CSV-W
* code-list
* literal
* resource (as in URI)

TODO: We need to flesh this list out a bit. We may also need to split this task out a bit.

This task is to create the initial glossary page with suitable definitions for the above listed terms. 

Each term should probably only be a few lines of explaination for now. We can flesh it out later.

**Comment by CharlesRendle** [comment]
Some terms off the top of my head (may or may not be relevant to the documentation's target audience):

- Data cube

- Multi measure

- RDF (triples)

- CSVW

- qb (especially when we use terms such as 'qb-flavoured')

- Codelist

- Ontologies + Schemas (SKOS, SDMX, e.c.t)

**Comment by CharlesRendle** [comment]
A few short non-fleshed out glossary definitions:

    • Dimension
      The dimension components serve to identify the observations. A set of values for all the dimension components is sufficient to identify a single observation. Examples of dimensions include the time to which the observation applies, or a geographic region which the observation covers.
      
    • Observation
      This is the actual data, the measured values. In a statistical table, the observations would be the values in the table cells.
      
      
    • Attribute
	The attribute components allow us to qualify and interpret the observed value(s). They 	enable specification of the units of measure, any scaling factors and metadata such as the 	status of the observation (e.g. estimated, provisional).

    • Measure
      The measure components represent the phenomenon being observed.


    • Unit
      A quantity or increment by which something is counted or described, such as kg, mm, °C, °F, monetary units such as Euro or US dollar, simple number counts or index numbers. The unit of measure in connection with the unit multiplier, provides the level of detail for the observation value of the dimension.


    • Tidy Data
      A format for laying out data sets. A tidy data set is arranged such that each dimension is a single column and each observation a single row.
	

    • URI
      Uniform Resource Identifier – URIs are used to name the entities and concepts so that consumers of the data can look-up those URIs to get more information, including links to other related URIs.


    • CSV-W
      Comma Separated Values on the Web – a standardised format to express useful metadata about CSV files and other kinds of tabular data.


    • Code List
      Predefined set of terms from which some statistical coded concepts take their values.

**Comment by robons** [comment]
Thanks for your efforts on this. I've made a few suggestions below.

It'd also be good to say where you've taken any existing definitions from.

> A few short non-fleshed out glossary definitions:
> 
> • Dimension
>   The dimension components serve to identify the observations. A set of values for all the dimension components is sufficient to identify a single observation. Examples of dimensions include the time to which the observation applies, or a geographic region which the observation covers.
>   
> • Observation
>   This is the actual data, the measured values. In a statistical table, the observations would be the values in the table cells.


I'm not sure exactly what you mean by this. The dimension's concepts are also values in table cells.

>   
>   
> • Attribute
> The attribute components allow us to qualify and interpret the observed value(s). They 	enable specification of the units of measure, any scaling factors and metadata such as the 	status of the observation (e.g. estimated, provisional).
> 
> • Measure
>   The measure components represent the phenomenon being observed.
> 
> 
> • Unit
>   A quantity or increment by which something is counted or described, such as kg, mm, °C, °F, monetary units such as Euro or US dollar, simple number counts or index numbers. The unit of measure in connection with the unit multiplier, provides the level of detail for the observation value of the dimension.
> 
> 
> • Tidy Data
>   A format for laying out data sets. A tidy data set is arranged such that each dimension is a single column and each observation a single row.

May be worthwhile linking to the [Hadley Wickham paper](https://www.jstatsoft.org/index.php/jss/article/view/v059i10/v59i10.pdf) from here.

> 
> • URI
>   Uniform Resource Identifier – URIs are used to name the entities and concepts so that consumers of the data can look-up those URIs to get more information, including links to other related URIs.
> 

May be worthwhile including some examples of URIs here, and noting that URLs are a type of URI. I'm wondering if there's somewhere good (other than wikipedia) we can link to for further information. 

> • CSV-W
>   Comma Separated Values on the Web – a standardised format to express useful metadata about CSV files and other kinds of tabular data.

Probably worthwhile linking to the W3C project page on this.
 
> 
> • Code List
>   Predefined set of terms from which some statistical coded concepts take their values.

A simple example of a code-list and concepts may be useful here.
