### ISSUE TITLE
set up a github repo to host these static sites (the API docs + this mkdocs stuff) 

### ISSUE THREAD

**Issue by MuazzamChaud** [GSS-Cogs/csvcubed#278]
alter the Jenkins job to publish to the appropriate repo

- [x] Set up a github repository inside GSS-Cogs to host the files.
  - [x] Make sure the github.io static hosting stuff is activated. 
-  [x] Using the existing credentials we have for github integration, find some kind of tool (perhaps plugin) for Jenkins that allows us to commit/publish files to a git(hub) repository at some point in a build.
- [x] Make sure that the static site publish only happens on the `main` branch build.
- [x] Test the website, to make sure that it works as we would expect
  - [x] Search works properly
  - [x] Navigation links in top work properly.
- [x] Make sure the main home page has some content explaining what the project is and what it's useful for (nothing too detailed, just a short summary).

**Comment by robons** [comment]
https://gss-cogs.github.io/csvcubed-docs/
