### ISSUE TITLE
Flow chart on how to fill in the Qube Config

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#295]
We need to create a flow chart to help users decide how they decide what goes into their JSON config file.

- e.g. Go through each of your columns and add it into the mapping section of the JSON file.
- For each column, decide whether it's a dimension/attribute/observed value/measure/unit - provide helpful info here to help them figure this process out - a series of questions they can ask themselves to figure it out.

- [ ] Share this flowchart with @garethlewis-ons

**Internal Use**

**Comment by robons** [comment]
Just a warning that we want to ensure the information is still accessible to people using screen-readers. If we can avoid using an image for this, all the better.

**Comment by canwaf** [comment]
Miro does support screen readers.

**Comment by robons** [comment]
> Miro does support screen readers.

To a limited extent

> Please, note, that the flow described above works the best for:
>
>    * Users invited to the existing team on the Enterprise Plan
>
>    * Users on Team, Business, Consultant, Education or Enterprise Plan that are invited directly to the board as anonymous Guest Editors  
>
> All of the flows described above are currently only available on the desktop. 

https://miro.com/accessibility-statement/improvements/
