### ISSUE TITLE
Deserialise Qube config and populate object (i.e. qube.read_config())

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#297]
This ticket provides two bits of functionality which would support users in csvcubed.

Ensure that the qube config file is validated prior to populating the object.

- [ ] Write a `qube.read_config()` function which takes the json file and populates the remainder of the object model of an already initialised qube
- [ ] Write a `initialise_qube_from_config()` function which returns the main qube object from the qube config file

As always, unit tests are required
- All column class types need to be tested (NewQbAttribute, ExistingQbDimension etc.)
- One measure/unit column configuration
- One measures/units are defined against the observation configuration

**Comment by robons** [comment]
We'll need to have a task to implement a CLI interface again in the csvcubed project since that got ripped out when we moved the info.json v1.1 stuff to gss-utils.

**Comment by robons** [comment]
Whoever takes up this task, make use of the [DataClassBase](https://github.com/GSS-Cogs/csvcubed/blob/main/csvcubed-models/csvcubedmodels/dataclassbase.py) class which will help with deserialisation from JSON.

**Comment by robons** [comment]
[This is how a good entry-point for how we're currently doing the deserialisation](https://github.com/GSS-Cogs/gss-utils/blob/csvwlib-integration/gssutils/csvcubedintegration/configloaders/infojson.py#L40).

When it comes to interpreting each individual column I'd only concern yourself with the [v1.1 approach](https://github.com/GSS-Cogs/gss-utils/blob/csvwlib-integration/gssutils/csvcubedintegration/configloaders/infojson.py#L163) and don't worry about the mess that lies below that.

**Comment by Giraffe-Technology** [comment]
Additional properties from MetadataCatalog class added to qbconfig-example.jsonc, and cube-config-schema updated.
Cube-Config Schema Documentation requires update and spellcheck.

**Comment by Giraffe-Technology** [comment]
Adding further unit tests and investigating an issue where code-list which should be value based is trying to refer to a local filesystem uri
