### ISSUE TITLE
JSONC Schema for Qube Config JSONCs

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#299]
Implement a JSON Schema for the Qube Config file.

Example: https://github.com/GSS-Cogs/csvcubed/blob/main/csvcubed/csvcubed/schema/qbconfig-example.jsonc
Existing `info.json` schema: https://github.com/GSS-Cogs/family-schemas/blob/main/dataset-schema-1.1.0.json
Existing `info.json` documentation: https://github.com/GSS-Cogs/gss-utils/blob/csvwlib-integration/gssutils/csvcubedintegration/configloaders/README.md

Base the schema off the existing info.json schema, ensuring that autocomplete and type hinting pops up in most IDEs (i.e. VSC and PyCharm)

- [ ] Support [Curies](https://www.w3.org/TR/curie/) for url-shortening fun

Column names must be case insensitive

**Comment by canwaf** [comment]
Help with measure columns: https://github.com/GSS-Cogs/gss-utils/blob/csvwlib-integration/gssutils/csvcubedintegration/configloaders/MeasuresColumns.md

**Comment by Giraffe-Technology** [comment]
Initial schema developed, 
Now (Mon 24th) proceeding to test & refine against convention and configuration cubes.

**Comment by Giraffe-Technology** [comment]
Second draft and corrections for missing hints(descriptions) pushed.
