### ISSUE TITLE
Detecting DataCube, CodeList and unsupported inputs

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#326]
Detect whether a given input json is a DataCube or a CodeList or an unsupported input (i.e. neither a DataCube nor a CodeList).

Reusing the code from pmdutils. 

- [x] Need some units tests to ensure this works reliably.
- [x] Copy and paste code for now, we don't want to create more projects that necessary right now.
  - [x] Put a comment stating that this is duplicated code and ideally would be refactored into a shared `utils` projecrt in future.

**Comment by canwaf** [comment]
Things that would be good for you to detect but not support are (i.e. tell people you're pointing it at the wrong file):
* table structure jsons (part of the csv-w payload)
* qube-config files
