### ISSUE TITLE
Displaying DataCube head, tail, n observation and val count

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#328]
Functionality:
- [x] Here's the first 3 lines and the last 3 lines... - head/tail (loaded CSV using pandas)
- [x] There are n observations (pandas)
- [x] And a value_count() of the observations broken down by measure and unit
  - [x] If it's a single measure cube, we need to extract the measure/unit from the DSD and then the count is simply the number of rows (observations) in the data frame.
  - [x] If it's a multi-measure cube, we need to look at the measure column to figure out the measure & look at the (technically optional) units column to find the unit 
       - [x] if there is no units column we need to get this from the DSD again.
- [x] Update json-ld loading functionality to load the relevant table schemas.
- [x] Need unit tests for the expected outputs of this functionality (i.e. the counts by measure, etc.)
- [x] Extend inspect cli behave tests to support the features in this ticket.

SPARQL queries required for:
  - [x] Finding out whether the dataset is multi-measure or single-measure.
  - [x] Finding out whether the dataset is multi-unit or single-unit.
  - [x] Extracting the single measure from the DSD
  - [x] Extracting the single unit from the DSD
  - [x] Figuring out which column is the measure column from the CSV-W metadata
  - [x] Figuring out which column is the units columns from the CSV-W metadata
  - [x] Finding the table schema files

**Comment by robons** [comment]
> * Finding out whether the dataset is multi-measure or single-measure.
> *  Extracting the single measure from the DSD
> *  Figuring out which column is the measure column from the CSV-W metadata
> *  Figuring out which column is the units columns from the CSV-W metadata

The above can all be done using the results of the existing components query (and inspecting the types returned).

> *  Finding out whether the dataset is multi-unit or single-unit.

This can be decided based on the number of distinct values within the CSV's units column (which you can figured out from the components query by looking for the (single) attribute component using the `http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure` URI; if you can find no such attribute-type component, then the dataset is a single-unit dataset.

I'll need to create SPARQL queries for the following:

> *  Extracting the single unit from the DSD

**Comment by robons** [comment]
Query to get the `url` of a given DataCube:

Note that you must bind a value to the `datasetUrlStr` parameter which is the `dataset` URI value from the first query.

```sparql
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


SELECT DISTINCT ?tableUrl
WHERE {   
    # Bind the URI of the dataset here.
    BIND ("final-uk-greenhouse-gas-emissions-national-statistics-1990-to-2020.csv#dataset" as ?datasetUrlStr).

    ?table csvw:url ?tableUrl.
    ?table csvw:tableSchema/csvw:column/rdf:rest*/rdf:first ?column.

    ?column csvw:propertyUrl ?columnPropertyUrl;
            csvw:valueUrl ?columnValueUrl.

    FILTER (str(?columnPropertyUrl) IN (str(qb:dataSet), "qb:dataSet")).
    FILTER (strends(str(?columnValueUrl), ?datasetUrlStr) || strends(?datasetUrlStr, str(?columnValueUrl))).
}    
```

**Comment by robons** [comment]
And this one will find a concept scheme inside a CSV-W and give you the URL of the CSV file. 

Make sure you check that you only get one result to avoid any potential problems like there being two concept schemed defined in the same file.


```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


SELECT DISTINCT ?conceptScheme ?tableUrl
WHERE {   
    {
        SELECT DISTINCT ?conceptScheme
        WHERE {
            ?conceptScheme a skos:ConceptScheme.
        }
    }

    BIND (str(?conceptScheme) as ?conceptSchemeUrlStr).

    ?table csvw:url ?tableUrl.
    ?table csvw:tableSchema/csvw:column/rdf:rest*/rdf:first ?column.

    ?column csvw:propertyUrl ?columnPropertyUrl;
            csvw:valueUrl ?columnValueUrl.

    FILTER (str(?columnPropertyUrl) IN (str(skos:inScheme), "skos:inScheme")).
    FILTER (strends(str(?columnValueUrl), ?conceptSchemeUrlStr) || strends(?conceptSchemeUrlStr, str(?columnValueUrl))).
}
```

**Comment by robons** [comment]
Here's a query to extract the unit URI and associated label (if it is defined locally):

You should check that only one result is returned, else something unexpected is happening.

```sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>

SELECT DISTINCT ?unitUri ?unitLabel
WHERE {   
    ?column csvw:propertyUrl  "http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure"^^csvw:uriTemplate;
            csvw:valueUrl ?unitUriTemplate.

    BIND(str(?unitUriTemplate) as ?unitUri).


    OPTIONAL {
        ?unit rdfs:label ?unitLabel.
        FILTER(strends(str(?unit), ?unitUri)).
    }
}    
```

**Comment by GDonRanasinghe** [comment]
@robons  When you are back, can you please check the below query which is for getting extracting Single Unit from DSD? It returns 0 results for me. The inputs I am using are attached. Also, just a friendly reminder - I am waiting for you to provide me the sparql for getting table schemas.

```PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>

SELECT DISTINCT ?unitUri ?unitLabel
WHERE {   
    ?column csvw:propertyUrl  "http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure"^^csvw:uriTemplate;
            csvw:valueUrl ?unitUriTemplate.

    BIND(str(?unitUriTemplate) as ?unitUri).


    OPTIONAL {
        ?unit rdfs:label ?unitLabel.
        FILTER(strends(str(?unit), ?unitUri)).
    }
}```

**Comment by robons** [comment]
Did you two end up getting this sorted out last week? I seem to recall something about you looking for a single-measure dataset.

**Comment by mikeAdamss** [comment]
progressed but not sorted, I think there's a few commented out tests still. there's missing functionality at the moment around not having the RDF for tableSchemas to query against yet.

**Comment by GDonRanasinghe** [comment]
Above is now resolved and available in the PR for reviewing.
