### ISSUE TITLE
local legacy codelists duplicate sort order

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#344]
Local legacy codelists are building with an error where the sort-priority duplicates and thus fails a SPARQL test. Workaround is delete the local codelist and have the codelist be generated by csvcubed.

https://github.com/GSS-Cogs/family-trade/pull/330 contains the workaround, and the issue.

Spike to look into what's going wrong here. Some local legacy codelists pass the SPARQL tests. If it's a simple fix do it as part of this ticket, otherwise create a new ticket to fix the problem.

**Comment by robons** [comment]
@canwaf could this be because the legacy upload pipeline on Jenkins hasn't been configured to delete the existing data which has already been uploaded to PMD?

**Comment by canwaf** [comment]
If it is one wonders why the specific error is two sort priorities. It seems like something else should have gone wrong?

**Comment by robons** [comment]
@canwaf Seems that deleting the data from the legacy pipeline fixed it, but could you check the same fixes the problems in other pipelines you've seen this problem with? Then we should be able to close the issue.

Thanks

**Comment by robons** [comment]
I'm assuming this issue has now been resolved.
