### ISSUE TITLE
Add published/created/modified dates to qube-config schema

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#358]
Right now the qube config schema doesn't support the published/created/modified dates. It should be added to the schema, and the documentation needs to be updated.

- [ ] Add the following (or similar) to the qube config schema to be headline metadata
```json
    "published": {
      "description": "The date and time it was published in ISO 8601 format as a string",
      "type": "string",
      "format": "datetime"
    },
    "created": {
      "description": "The date and time it was created in ISO 8601 format as a string",
      "type": "string",
      "format": "datetime"
    },
    "modified": {
      "description": "The date and time it was modified in ISO 8601 format as a string",
      "type": "string",
      "format": "datetime"
    },
```
- [ ] Update documentation: external-docs/docs/guides/qube-config.md

**Comment by robons** [comment]
This should be part of the Application Profile work now, or else will be possible when we support JSON-LD qube-config files in #712™
