### ISSUE TITLE
Support the removal of `.csv` from CSV-W generated URIs

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#378]
From @rossbowen:

> can we get the .csv dropped from URIs in csvcubed, or maybe exposed as an option? We’re probably going to start work on refreshing the climate data soon (which does give an opportunity to start using csvcubed) but I’d have a preference for dataset URIs to be similar (i.e. not with the .csv ) to those coined last year

The reason we include the `.csv` on the end of URLs generated inside the CSV-W is so that when a user uploads a CSV-W to their wordpress (or similar) site, the URIs should dereference somewhere sensible (i.e. to a file which exists on their server and is related to the data.)

As part of this task, could you please:

- [x] Add a *URL style* property to the `Cube` class' constructor in csvcubed which allows a user to specify the style of URLs that csvcubed should generate.
  - The type of this property should be an enum which currently has values similar to `Standard` and `WithoutFileExtensions`
- [x] (gss-utils) Add the ability to specify a value in the info.json v1.1 format which allows the user to configure the url style generated by csvcubed.  
   - This should be picked up by the `infojson2csvw build` command and used to configure the `Cube` using the new parameter you've added above. 
   - N.B. you must update the JSON schema as well as the code.
- [x] Write unit/behaviour tests for everything
- [x] Update the appropriate documentation in gss-utils to make reference to this new functionality.

**Comment by goofballLogic** [comment]
https://github.com/GSS-Cogs/gss-utils/issues/356

**Comment by goofballLogic** [comment]
Part of this is: https://github.com/GSS-Cogs/family-schemas/issues/7
