### ISSUE TITLE
Bug: cube config json should be able to deal with characters which are URI illegal in metadata 'id' property

### ISSUE THREAD

**Issue by Giraffe-Technology** [GSS-Cogs/csvcubed#380]
We need to change the logic of the JSON metadata loader so that it replaces any URI-illegal chars in the `ID` property so that it generates a safe URI for the datasets.

- [ ] If the id differs from what the user inputted, we should log a warning the the console/log file.

**Comment by Giraffe-Technology** [comment]
When the cube config json contains an id of 'http://schema-id' the following error is produced as it contains illegal characters that cannot be used in construction of the output filenames
CRITICAL:csvcubed.cli.entrypoint:Traceback (most recent call last):
  File "C:\Users\Richard\OneDrive\Documents\Methods\ONS\git\csvcubed\csvcubed\csvcubed\cli\entrypoint.py", line 83, in build_command
    build(
  File "C:\Users\Richard\OneDrive\Documents\Methods\ONS\git\csvcubed\csvcubed\csvcubed\cli\build.py", line 78, in build
    writer.write(output_directory)
  File "C:\Users\Richard\OneDrive\Documents\Methods\ONS\git\csvcubed\csvcubed\csvcubed\writers\qbwriter.py", line 123, in write
    with open(metadata_json_output_path, "w+") as f:
OSError: [Errno 22] Invalid argument: 'out\\example_output\\http:\\schema-id.csv-metadata.json'

**Comment by robons** [comment]
Sorry @CharlesRendle but I made this fix whilst I was doing something in the area in the following PR: https://github.com/GSS-Cogs/csvcubed/pull/430
