### ISSUE TITLE
looks_like_uri returns True when testing a fully qualified(windows) path

### ISSUE THREAD

**Issue by Giraffe-Technology** [GSS-Cogs/csvcubed#381]

**Comment by robons** [comment]
@goofballLogic This may be a good first issue for you.

The code can be found [here](https://github.com/GSS-Cogs/csvcubed/blob/main/csvcubed/csvcubed/utils/uri.py#L66) and the place you should add/modify unit tests is [here](https://github.com/GSS-Cogs/csvcubed/blob/main/csvcubed/tests/unit/utils/test_uritests.py).

If you struggle to get the unit tests running, it may be worth while us having a chat.
