### ISSUE TITLE
Use local copy of files if HTTP fails

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#401]
This issue was raised due to a user of csvcubed being unable to access certain web resources due to them being behind a proxy server which white/black-lists various domains. This meant a user had an internet connection but wasn't able to load the resources that csvcubed was trying to load.

- If any of the HTTP request for the following files fails (for any reason, i.e. non-2xx HTTP status code) then our function should return the contents of the file from disk as if the HTTP request had succeeded (with an additional warning log printed in the log).
  - [ ] qube-config.json SCHEMA
  - [ ] code-list-config.json SCHEMA
  - [ ] qube-config templates

There are a few ways this could be implemented:

- Using the requests cache functionality we have defined in [cache.py](https://github.com/GSS-Cogs/csvcubed/blob/main/src/csvcubed/utils/cache.py), we could write the local files to the cache for use if the external HTTP request fails. This might not be possible.
- If the above isn't possible, we could also use a python request mocking library so long as it attempts to fetch the remote content before falling back on the local content.
- If the above isn't possible, we can simply update the three functions with logic to check for HTTP request failure and manually serve up the contents for the specific file requested.

If you don't managed to complete this within 8 points of effort, note down what the best approach is and create  new ticket to implement it.

**Comment by robons** [comment]
https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/

Hooks on the session object (the cached session) may be a suitable location to implement this.
