### ISSUE TITLE
Guess column types from dataframe

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#41]
Ability to guess whether a column is measure/dimension/attribute and present the user with the tool's guess at runtime, similar to how R's `readr::read_csv` or other CSV parsers work.

We can accept poor "guesses" at first - e.g., if a column is entirely numeric, assume it is a measure.

Report back to the user what the programme has guessed, like `read_csv`:

```r
> readr::read_csv("https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv")

#> ── Column specification ────────────────────────────────────────────
#> cols(
#>   John = col_character(),
#>   Doe = col_character(),
#>   `120 jefferson st.` = col_character(),
#>   Riverside = col_character(),
#>   NJ = col_character(),
#>   `08075` = col_character()
#> )
```

**Comment by robons** [comment]
I think this is superceded by the configuration by convention approach used in csvcubed.
