### ISSUE TITLE
Support markdown in description

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#411]
The json key for description is `dcterms:description`, this needs to be able to be made Markdown

- [x] Add documentation saying that the description field is always markdown
- [x] Serialise the CSV-W accordingly by adding the datatype to the field so that is marked as markdown (speak to @robons about this)

- [x] We should not support arbitrary HTML at all in the markdown field to avoid HTML-injection. Users should be warned about it.
  - Ideally select a small markdown library which supports checking for raw HTML inside markdown - if this doesn't seem reasonable we'll come up with a regex to match on any HTML tag. 

Create an issue in the pmd-jenkins-library to do the thing
- [x] Alter the upload to pmd pipeline such that the `dcterms:description` field is replaced `pdmcat:markdownDescription` field - see the [PMD4 Application Profile](https://swirrl.github.io/PMD-AP/index.html#dataset) for more information.
- [x] Make sure this actually works since it's not something that can be tested within csvcubed

**Comment by robons** [comment]
Here's something I knocked up to help you check whether some markdown contains any HTML. As discussed previously, it'll be overly sensitive but it'll be good enough given that we're just warning the user.

```python
from html.parser import HTMLParser


class ContainsHtmlParser(HTMLParser):
    contains_html: bool = False

    def handle_starttag(self, tag, attrs):
        self.contains_html = True

    def handle_endtag(self, tag):
        self.contains_html = True



parser = ContainsHtmlParser()
parser.feed("""
    # This is some example markdown
    ```html
        Some example nonsense <p>hi</p>
    ```
""")
print(parser.contains_html)
```

**Comment by robons** [comment]
@MuazzamChaud: I've completed issue #485 which defined the shape of RDF outputs from csvcubed.

Given you're changing the shape of one of these outputs (by setting the data-type) could you make sure to create a new version of the code-list shape with your changes applied to it?
