### ISSUE TITLE
Add Windows environment testing to release procedure

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#429]
We should provide instructions on how to spin up the windows Virtual Machine @robons  has set up in GCP and get the users to run unit + behaviour tests.

Unfortunately behaviour testing isn't working at the moment due to the virtual machine being ill-configured for virtualisation (and so can't run linux docker images). You should try to ensure that the virtual machine is configured appropriately as part of this ticket.

**Comment by mikeAdamss** [comment]
added some documentation, needs a sanity check before I'd consider this done: https://collaborate2.ons.gov.uk/confluence/display/PHEM/Release+Procedure

**Comment by robons** [comment]
I've gone through it and made a few additions but it mostly looks good to me.

**Comment by robons** [comment]
I've gone through it and made a few additions but it mostly looks good to me.
