### ISSUE TITLE
Restructure individual projects

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#446]
- [ ] Each project should only contain relevant packages, source code and tests (i.e. unit and feature tests).
- [ ] Each project should contain an individualised dev container and the corresponding docker file.
- [ ] The external docs (i.e. mkdocs) need to be inside the `csvcubed` project.
- [ ] The API docs (i.e. sphinx docs) needs to be removed.
- [ ] Each project should contain the following project structure:

```
- <project-name>
    - .devcontainer
      - devcontainer.json
    - Dockerfile
    - .gitignore
    - src
      - <package-name>
        - __init__.py
        - <rest of the source code>
    - tests
      - test-cases
      - unit
      - features
    - poetry.lock
    - pyproject.toml
    - tox.ini
    - Jenkinsfile
    - README.md
    - LICENSE
    - dist/
```

- project-name  - can be csvcubed , csvcubed-devtools , csvcubed-models or csvcubed-pmd.
- .devcontainer  - this includes the docker container definition (i.e. the devcontainer.json).
- Dockerfile  - this is the docker file used by the dev container.
  - [ ] We should be referencing the poetry.lock & pyproject.toml files in the docker file and installing all dependencies on a docker-container-wide basis.
- .gitignore  - any files/folder paths we should not be committing to the repo.
- src/ - this will contain the source code under the <package-name>  folder. The project will be compiled with <package-name> when we want to deploy to pypi. So that a project can import another using the package name. For example, from <package_name> import example.  See https://packaging.python.org/en/latest/tutorials/packaging-projects/ for reference.
- tests/ - this will contain our unit and behaviour tests. And any prerequisites for the tests (e.g. test-cases/).
- poetry.lock and pyproject.toml - these will contain the dependencies the individual project require. We are not going to add any shared dependencies here as the projects are now isolated into individual git repos.
- Jenkinsfile - jenkins pipeline config of the individual project.
- tox.ini - this is for the tox stage of the jenkins pipeline.
- README.md - read me file of the individual project.
- LICENSE - will contain the license information for the individual project.

**Comment by robons** [comment]
Can we do this process on a project-by-project basis? That way we don't end up having to stop the world. Perhaps a suitable order would be:

* Devtools
* The PMD project
* models
* the main csvcubed project 

At each step we could remove the project from the main csvcubed repo once we have each independent project/repo set up. And we would be practicing with the projects with the least impact first.

Alternatively if we want to speed it up a bit we could do two phases:

* Move devtools + PMD out of csvcubed
* Move models out of csvcubed.
