### ISSUE TITLE
PyPi Install & Use csvcubed Issues

### ISSUE THREAD

**Issue by Giraffe-Technology** [GSS-Cogs/csvcubed#453]

**Comment by Giraffe-Technology** [comment]
Using Pycharm with a new python 3.9 virtual env using virtualenv and running 'pip install csvcubed'
Then, from a terminal, within the venv, run 'csvcubed build'
reveals unmet package dependencies for rdflib and csvcubed.models

**Comment by robons** [comment]
Known issue
