### ISSUE TITLE
Set up the Tox docker container and deploy it on docker hub

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#458]
- [x] Take the Tox Dockerfile from the csvcubed repo.
- [x] Deploy the container on docker hub (using github actions). -- Probably from a new repo you create for this purpose.
- [x] Once the new container has been pushed to docker hub, you should update the Jenkins file in the csvcubed repo so that it uses this image instead of building from the Dockerfile itself -- make sure to remove the docker file from the repo too!.

**Comment by mikeAdamss** [comment]
https://github.com/GSS-Cogs/csvcubed/pull/465
