### ISSUE TITLE
Trial use of Swirrl's AOT-compiles csv2rdf binary in docker

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#459]
Swirrl provide a (beta) version of csv2rdf which is AOT using GraalVM (I think) which is designed to limit the startup-overheads which should reduce the amount of time we spend in behaviour tests.

I believe that @ajtucker did some work to bring this into a docker image. If not, that needs to be created as part of this task. N.B. do not publish it to gsscogs/csv2rdf:latest (give it a seperate tag at least so no one accidentally uses it).

- [ ] Alter the csv2rdf behaviour test functionality in the devtools package and ensure that it uses the special docker container containing the AOT-compiled binary.
- [ ] Do some benchmarking to show us the performance improvements in behaviour testing (if any) with files of various sizes (ideally).

**Comment by mikeAdamss** [comment]
https://github.com/GSS-Cogs/csvcubed/pull/464
