### ISSUE TITLE
code list schema json top and bottom concepts

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#463]
The schema developed in #294 allows the user to sort by label or notation. And use ascending or descending sort methods. Or use the `sort_order` property within the concept which allows the user to define the sort order for each concept manually.

In some use cases however, the users would like to see a certain number of concepts at the bottom or top of the list, without caring or caring about how the rest of the concepts are ordered. (e.g. @canwaf can you please add an example use cause or two here?).

User can do this using the `sort_order` field in the current sorting mechanism. However, this means the user will have to define the sort_order for all the concepts in order to get a set of concepts to the top of bottom of the list. For example, lets say there there are 1000 concepts and user would like to get 5 of these concepts to the top of the list. In order to do this using the current sorting mechanism, the user will have to define the the sort order for all the 1000 concepts so that the 1st concept will have a sort order of 1000 and the 5 concepts that need to be displayed at the top will have sort orders of 1 to 5.

This ticket involves investigating how we can improve the sorting mechanism or introducing a new mechanism in code list schema to make the above feature less cumbersome for the user. Potential options are: 

(i) Defining two new fields called `top_concepts` and `bottom_concepts` that will allow the user to `$ref` the concepts that need to be displayed at the top or bottom. At the schema level, these fields will not have anything to do with the sort fields. But at the code level, we will be making sure the concepts referenced in the `top_concepts` field will appear at the top, and appear at the bottom for the `bottom_concepts`.

(ii) Using negative values in sort?

(iii) Allow both the sort_order and sort_method to be defined. And then ask user to define sort_order for the concepts that needs to go to the top or button only. Sort order for the rest of the concepts can be undefined?

**Comment by robons** [comment]
We seems to be able to do this already by specifying the sort order manually on the ones we want to be at the top or the bottom:

The following moves the `second` concept to the end of the list, it is also possible to move the `second` concept to the beginning of the list by setting the sort order to `0`.

```json
{
    "$schema": "https://purl.org/csv-cubed/qube-config/v1",
    "title": "Some title",
    "columns": {
        "Some Dimension": {
            "type": "dimension",
            "code_list": {
                "title": "Some code list",
                "concepts": [
                    {
                        "label": "First",
                        "notation": "1"
                    },
                    {
                        "label": "Second",
                        "notation": "2",
                        "sort_order": 2
                    },
                    {
                        "label": "Third",
                        "notation": "3"
                    }
                ]
            }
        }
    }
}
```

**Comment by GDonRanasinghe** [comment]
Closing this ticket as we can already do this as per the comment from Rob above.
