### ISSUE TITLE
Publish Eurovision Dataset on PMD

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#471]
This is the dataset used as part of the quick-start guide.

- [x] Make sure that the quick start guide's CSV-W has been published somewhere internet accessible (i.e. in a github repo or similar).
  - It appears that the outputs are available [here in github](https://github.com/GSS-Cogs/csvcubed-demo/tree/main/full_out)
- [x] Create a new job in Jenkins which reuses the `upload-to-pmd` pipeline current used by the in-house team which converts and uploads the contents of a CSV-W to PMD.
  - Documentation is available [here](https://collaborate2.ons.gov.uk/confluence/display/PHEM/Jenkins+-+Uploading+a+CSV-W+to+PMD).
  - n.b. we'll be using the `csvwUrl` param instead of the `csvwGenerationProjectName` to define where we get the CSV-W from.
- Make sure we publish the dataset on staging.

- [x] Negotate with @rossbowen to get the dataset published on the beta (public-facing) website.

An example build pipeline has the following script:

```
      @Library('pmd@csvwlib-build') _

      csvw2pmd {
          csvwGenerationProjectName = "DIT-UK-tariffs"
          graphUriBase = "http://gss-data.org.uk/graph/trade/dit-uk-tariffs"
          resourcesUriBase = "http://gss-data.org.uk/data/trade/dit-uk-tariffs"
          shouldPublish = false
      }
```

**Comment by robons** [comment]
Work is currently with @canwaf who is rebuilding the eurovision datasets using csvcubed==0.1.4 and then triggering the Jenkins upload pipeline to publish the data on staging PMD.

**Comment by canwaf** [comment]
There is a problem with the full dataset because we have made a conscious decision to break the RDFQB Vocab over its insistence on an observation value per observation. Otherwise the no_missing one published immediately.

**Comment by canwaf** [comment]
There is a problem with the full dataset because we have made a conscious decision to break the RDFQB Vocab over its insistence on an observation value per observation. Otherwise the no_missing one published immediately.
