### ISSUE TITLE
GitHub action create CSV-W from csv upload to repo

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#472]
This task is to create an example github action which takes a CSV and (appropriately named) JSON configuration file and builds the CSV-W artifacts for the user.

This means the user does not have to install any of our tooling on their local machines which may be difficult in some organisations. This is primarily aimed at users who are using open data, so that they are able to make use of the free github actions for open source repos.

- [x] Allow users to create as many folders as they like (with hierarchical structure) and ensure that the action can be configured to build *all* of the CSV-Ws from individual folders.
- [x] Decide on some convention by which the action can figure out which file is the CSV and which file is the JSON config in each folder & make sure to document this for users.
- [x] Make sure to run a csvcubed inspect on all CSV-Ws output from csvcubed - once build is complete.

- [x] The inspect command output should be stored in a text file which is stored as an artifact in the gh action.
- [x] Make sure the CSV-Ws are recorded and stored as artifacts in github actions.
- [x] Provide the ability to publish artifacts to github pages. 
- [x] Ideally we can provide URLs which we print in the output to let the user know where these artifacts will be published.
- [x] Make sure all artifacts are archived even if an error occurs in the build after the arfiact has been generated.
- [x] Good documentation should be available within the csvcubed external docs to show users how they can set this up on their own github repo.

As it's a spike, see how far you can get down the list - it'll make a good demonstration in the sprint review.

**Comment by CharlesRendle** [comment]
Ended up making no commit-able progress with this ticket over my working days.

**Comment by GDonRanasinghe** [comment]
The repository which includes the example action is at: https://github.com/GDonRanasinghe/csv-to-csvw.

**Comment by GDonRanasinghe** [comment]
@robons FYI: I've changed the final estimate of this spike from 8 days to 13 days. This is the amount of time it took me to investigate and develop, document and update according to PR feedback (this is WIP).

**Comment by mikeAdamss** [comment]
I can't find the pr - did we merge already?

Before I comment I wanted to say this is excellent and as a spike I would regard this as done (you've spiked how to implement the functionality we want), but there's a little conceptual confusion here that I wanted to clarify as I think there is some follow up work to do (depending on Robs priorities ofc).

So this isn't a github action - it's a repo _using_ multiple github actions.

so for example, if you could do something like this:

yaml
```
- name: Output CSVW
        uses: gss-cogs/csv-to-csvw
```

then `gss-cogs/csv-to-csvw` would be the github action, i.e a distinct callable application that "performs an action" when referenced within a CI/CD workflow - hope that makes sense.

I suspect that what we need is:

a.) To _publish_ a github  action, as per above example, so other `.github/workflow/*.yaml`'s, can make use of it - including ....
b.) This _example_ repo with a walkthrough that people can branch to get started (i.e what you've already got, but with the actually executable steps pulled out and published elsewhere as a distinct tool in of itself).

The idea being that (to use my example) `gss-cogs/csv-to-csvw` is a distinct software release (latest), if we update it then (unless they've pinned it) those updates go downstream to all the branched examples plus anyone using the action directly in their own workflow.

This last comment is unconnected and pretty unfortunate as this all reads really well, but all your screenshots have got your personal Github in them, and I wouldn't bother with the first one at all, its probably redundant.

Again, great work and I would 100% stop working on this and consider this spike a success. If or what we do further on this will depend on @Robons priorities and whether or not he tells me I'm totally wrong about all the above :smile:

**Comment by GDonRanasinghe** [comment]
@mikeAdamss Thanks for the feedback. There is no PR for this - the work is in the https://github.com/GSS-Cogs/csv-to-csvw repository. The user flow is explained in the following video - https://onswebsite.slack.com/archives/C0281HDGA1M/p1655366124164179. I will send it in slack directly as well.

**Comment by robons** [comment]
Just having a quick catch-up with lots of things so I'll just fire a couple of points into this discuss:

* I definitely think this spike can be considered completed once @canwaf 's  requested changes on the [docs PR](https://github.com/GSS-Cogs/csvcubed/pull/530/) have occurred. 
* I definitely like @mikeAdamss ' suggestion of it being a separate github action that users can add into their build scripts themselves - ideally being able to configure where the outputs go i.e. `commit_outputs_to_git=False, commit_outputs_to_gh_pages=True, just_process_this_file='some-folder/some-file-i-want-to-process.csv-metadata.json'`, etc.
* I'll take a deeper look at the code to see if there are any other changes at some point soon.

Nice work @GDonRanasinghe - if you could demo this at the sprint review on Wednesday that would be great. I know Swirrl and others are interested in this.
