### ISSUE TITLE
Documentation improvements following release and user research

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#491]
## Initial ticket
Following the release of csvcubed 0.1.1, we've got a few changes which need to be made. First, csvcubed-models is now correctly identified as a dependency of csvcubed, so we just need users to `pip install csvcubed`. This change is already reflected in the Quickstart installation.

Additionally, the Quickstart videos explained a bug, which has been fixed. We need to rerecord both the voice over and the screen cast which shows the year code list not being generated.

## User research changes
First, shout out to @JohnLewisUR for being the user for User Research and taking the time to learn how to use a CLI!

The Quickstart contains a lot of links, and users are under the mistaken belief they need to click them. By clicking on these links users are introduced to our much more in-depth guides and no longer on the Quickstart page. To get users focused on the task at hand, descriptions and links which are not absolutely for them to accomplish the specific task for that page should be removed for focus and clarity.

* Boilerplate commands which will not work belong in How-to guides, not Quickstart

### Quickstart-wide changes
Videos should be more prominent (i.e. at the top), since they provide an complimentary but not exhaustive reproduction of the page's content.

### Installation
Installation page should only cover the installation of csvcubed. The predecessor steps should be covered in a guide (i.e. how to install miniconda, set up a python environment etc), and that the Prerequisites should be referenced with a link to that guide.

- [x] Clarify the "follow along" prerequisites (Have python 3.9 or 3.10 installed)
- [x] Move video embeds to top of page
- [x] Remove miniconda installation steps to guide
- [x] Encourage the user to copy an paste the commands into their terminal

### Designing a CSV
Configuration by convention vs explicit configuration section is confusing the point of this page, which is to introduce standard form.

- [x] Clarify the "follow along" prerequisites (Have csvcubed installed)
- [x] Move video embeds to top of page
- [x] Remove explicit configuration introduction from this page
- [x] Rewrite to say that there are other ways to configure which are introduced later
- [x] Highlight that the data should be downloaded to follow along with the next steps

### Building a CSV-W
User research said the video of showing the contents of the files made more sense. 

- [x] Clarify the "follow along" prerequisites (Have sweden at eurovision no missing in their cwd)
- [x] Move video embeds to top of page
- [x] Update build complete message with example of path, explaining what the path means
- [x] Clarify that a code list is a list of unique values in that column
- [x] Explain that metadata means descriptive information about that column or data set
- [x] Explain that schema means the machine-readable format information about that column or data set
- [x] Explain that the schema and metadata files are combined for the main data set

### Describing your CSV
Writing json was challenging for our user, and even the copy of the pre-written catalogue information and saving it needed clarification.

- [x] Clarify the "follow along" prerequisites (Have build your cube in the previous step)
- [x] Move video embeds to top of page
- [ ] Link to GitHub.dev or similar which provides a web-based json schema-aware development environment which will allow the user to download their work
- [ ] Rerecord the video showing using this interface instead of VSC directly

### Linking data
Now we can describe explicit configuration. We should mention that anything in the configuration file overrides the defaults seen without passing the config command. Provide a working `csvcubed build csv -c json` command provided they followed the previous steps.

- [x] Clarify the "follow along" prerequisites (Have your "no_missing.json" file ready to go)
- [x] Move video embeds to top of page
- [ ] Link to GitHub.dev or similar which provides a web-based json schema-aware development environment which will allow the user to download their work

### Inspecting a CSV-W
This was fine.

- [x] Clarify the "follow along" prerequisites (Have your fully built CSV-W file ready to go)
- [x] Move video embeds to top of page

**Comment by robons** [comment]
> The Quickstart contains a lot of links, and users are under the mistaken belief they need to click them. By clicking on these links users are introduced to our much more in-depth guides and no longer on the Quickstart page. To get users focused on the task at hand, descriptions and links which are not absolutely for them to accomplish the specific task for that page should be removed for focus and clarity.

I disagree with this. I always find deep links within documentation useful to help me learn more. I don't understand why anyone would expect that they have to click them.

If you can point me to some evidence that proves I'm wrong, I'm more than willing to take a look.

> Boilerplate commands which will not work

I'm confused why we'll have commands that won't work.

> Videos should be more prominent (i.e. at the top),

That sounds sensible.

>  Link to GitHub.dev or similar which provides a web-based json schema-aware development environment which will allow the user to download their work

I investigated this but found that the schema auto-complete didn't work that effectively in the browser version.

> Now we can describe explicit configuration

I think that should be separate from the linking data section. Perhaps add another section before linking data?

The rest of it seems to be broadly fine from my perspective.

**Comment by canwaf** [comment]
> I disagree with this. I always find deep links within documentation useful to help me learn more. I don't understand why anyone would expect that they have to click them.
> 
> If you can point me to some evidence that proves I'm wrong, I'm more than willing to take a look.

I have a sample size right now of `n=1`, and John getting confused about why he was taken to a super detailed page when he was just getting started.

> I'm confused why we'll have commands that won't work.

https://gss-cogs.github.io/csvcubed-docs/external/quick-start/build/#passing-configuration, there is no config file yet. We also don't have a `cd out/` bit following build for inspect.

> I investigated this but found that the schema auto-complete didn't work that effectively in the browser version.
Drat. I'll get people to just download the samples so they don't have to write them or save them.

> I think that should be separate from the linking data section. Perhaps add another section before linking data?

We describe (explicit) and link (explicit). I don't think the distinction is necessary for a Quickstart user. Saying "There are two options but we're ignoring the complex one for the Quickstart" is the same as just ignoring the complex one for the Quickstart. Maybe instead of the complex next steps section to obsStatus columns should be learning about explicit configuration?

**Comment by canwaf** [comment]
Won't do the Google code shell quite yet, I like VSC for this kind of thing; however in tutorials (i.e. not quick starts nor guides) it would be good to use it.
