### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/csvcubed#504]
DCAT 1 & 2 suggest that contact details should use VCARD, https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/#Property:dataset_contactPoint and https://www.w3.org/TR/vocab-dcat-2/#Property:resource_contact_point

We're currently using mailto: URIs as both the `dcat:contactPoint` and the `pmd:contactEmail`, but should aim for https://www.w3.org/TR/vcard-rdf/#Examples

Need to figure out the support for this in PMD /cc @BillSwirrl .

**Comment by robons** [comment]
Closing this as we'll have our application profile decided on soon, we can't do anything until that's complete.

**Comment by robons** [comment]
Closing this as we'll have our application profile decided on soon, we can't do anything until that's complete.
