### ISSUE TITLE
Load model from CSV-W

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#51]
Currently already loading from SKOS Codelists ([Codelist reader class](https://github.com/GSS-Cogs/csvwlib/blob/main/csvqb/csvqb/readers/skoscodelistreader.py); however this doesn't address the qube's csvw itself.

**Comment by robons** [comment]
It'd be nice to be able to load the full model in memory using the inspect API but I don't think we have a clear use-case for it just yet.
