### ISSUE TITLE
Code List Config `same_as` field not serialised to CSV-W

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#518]
When the user specifies a `same_as` relation between a concept in their new code list and an existing concept defined elsewhere, the information is not serialised into the code list CSV-W.

We need to make sure that the same as relationship is serialised correctly into the CSV-W. This means adding the column to the CSV file as well as adding the `owl:sameAs` relationship to the column definition.

Refactor behave tests in cube feature.

**Comment by GDonRanasinghe** [comment]
@robons I've updated the effort in this ticket from 3 to 5 as this involved an additional task - refactoring behave tests in the cube feature. I have refactored all the tests in the cube feature.

**Comment by canwaf** [comment]
This is an example of it not serialising the same_as provided in a concept scheme. https://github.com/GSS-Cogs/family-climate-change/tree/master/datasets/Forestry-Research-Forestry-Statistics-2022-Carbon

**Comment by canwaf** [comment]
Scoring: Impact is high: the functionality is not accessible and there is no workaround. Probability is moderate: users who want mixed-concept schemes will be impacted, which account for large number of datasets but not the majority.

This makes this bug critical.
