### ISSUE TITLE
Add "How to write metadata" guide or procedure

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#520]
Add a new page of documentation guiding a user through how to write their metadata in the qube-config.json file. The current file is a bit too technical for most users and doesn't provide them with examples.

- [ ] Guide users through all of the fields they can use, explain to them what the field contains and provide examples for them to choose from.
- [ ] Link back to the existing qube-config.json for more advanced configuration options.
- [ ] Explain what the squiggly lines in vscode mean and show auto-completion
- [ ] Give them lots of examples of JSON documents they can copy & paste.

- Probably want multiple pages
- Guide to defining the metadata
- Guide to defining columns

See the below from #706 for more thoughts and ideas. This seems to be a duplicate ticket.

------------

Following on from the completion of #648, the following suggestions have been identified to improve the user guidance on writing a qube-config.json file:

[General comments:](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/)

- [ ] Resolve whether the terminology is “qube-config” or “cube-config” (all pages) (include in [Confluence Style Guide](https://confluence.ons.gov.uk/display/PHEM/Style+Guide))
- [ ] Resolve whether csv and uri should be capitalised or not (all pages) (include in [Confluence Style Guide](https://confluence.ons.gov.uk/display/PHEM/Style+Guide))
- [ ] Include a link to the current qube-config schema
- [ ] Use one data set throughout guide (if feasible)

[Column definitions](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#column-definitions)

- [ ] “Using existing columns” section could do with better explanations - e.g. “Unless the component being reused is a literal attribute and you're providing a "data_type" key-value pair, any other key-value pairs provided will change the column to a new component which will extend the linked parent component.”
- [ ] For components other than Dimension - make it clearer that “type” will default to “dimension” unless explicitly stated
- [ ] Include explanations about New/Existing - existing where?
- [ ] Reorder tables to match the order in the schema

[Shared column configuration option](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#shared-column-configuration-options)

- [ ] Repetitive - could be incorporated into individual sections

[Measures and Units](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/#measures-and-units)

- [ ] Make it clearer that the properties in the table go inside the “values” property for measures/units

The new User Guide should link to the [existing reference documentation](https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/qube-config/) where appropriate. The reference documentation could be further amended to minimise repetition between the two documents and direct users to the User Guide for configuration examples.

**Comment by robons** [comment]
As part of this ticket, can you also review the location of our log files. Check the [AppDirs](https://github.com/ActiveState/appdirs) package to see if they've updated their documentation to point out where user logs now get stored.

Can you use this information to update the log path [in our docs](https://gss-cogs.github.io/csvcubed-docs/external/guides/command-line/logging/#log-output) so users can sensibly find the logs.
