### ISSUE TITLE
prov-o:createdUsing csvcubed-version in CSV-W

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#541]
This new triple just tells someone which version of csvcubed was used to build the CSV-W. We should attach it to the `dcat:Dataset`.

- [ ] Use a URI to represent the version of csvcubed. Perhaps this should be the URI of the github release? e.g. https://github.com/GSS-Cogs/csvcubed/releases/tag/v0.1.4 -- just use string concatenation to build this, don't bother checking whether it actually exists.

**Comment by robons** [comment]
```
<http://example.com/some-code-list> provo:wasGeneratedBy <http://example.com/some-activity>.
<http://example.com/some-code-list> a prov:Entity.                

<http://example.com/some-activity> provo:used <http://github.com/v0.1.4>.                                                   
<http://example.com/some-activity> a provo:Activity.
 ```

**Comment by robons** [comment]
This can't be closed as complete. It should be moved to the `awaiting release` column in Zenhub and only closed when it's actually released.
