### ISSUE TITLE
column mappings can NOT be allowed to let the user specify both cell_uri_template and values

### ISSUE THREAD

**Issue by MuazzamChaud** [GSS-Cogs/csvcubed#550]
change the v1_2 schema.json (@ https://github.com/GSS-Cogs/csvcubed/blob/main/src/csvcubed/schema/cube-config/v1_2/schema.json) to have the user only able to add values OR cell_uri_template to units and measures column mappings, as well as making the same change to any other columns that allow this.

This is likely a minor change since we're just fixing a bug in the existing JSON schema for a configuration that csvcubed was never able to successfully read.

- [x] Write a unit test to ensure that a schema with the new version is correctly loaded and parsed.

This bug has been triaged as low priority, however it is a relatively small alteration when done in conjunction with other Qube-Config schema changes. If you're doing any updates to the qube-config.json schema, PLEASE include this as part of your change.

**Comment by GDonRanasinghe** [comment]
The new behave tests written in https://github.com/GSS-Cogs/csvcubed/pull/571 covers the tests for this change as well.
