### ISSUE TITLE
Process of Triaging Bugs

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#562]
We need some kind of formalised process for deciding what the severity of a bug is and the appropriate action/urgency of the resolution.

The idea is that anyone can take the process document and take the bug they have just been told about and decide whether the bug needs to be fixed immediately, whether it can sit for a few days or whether it can wait for a few sprints before being fixed + released.

We can have a nice diagram in miro but we also need some basic text that can sit anywhere else, e.g. confluence, perhaps github.

- [x] Run it past other team members to figure out if they can select the right severity for some hypothetical bugs.

**Comment by canwaf** [comment]
Document is on confluence, link is in slack.
