### ISSUE TITLE
Stress-test csvcubed

### ISSUE THREAD

**Issue by GDonRanasinghe** [GSS-Cogs/csvcubed#563]
We should stress-test csvcubed to identify its limits. Examples of parameters we can test are:
1. Size of data sets
2. Device storage capacity
3. Device memory/RAM

Need to test `csvcubed build` and `csvcubed inspect` (with the outputs from the build command) for the following sizes of CSV:

- [ ] 10,000 rows
- [ ] 100,000 rows
- [ ] 1,000,000 rows
- [ ] 1,000,000,000 rows (We don't have to do this one if the smaller sizes seem to take far too long (over hours)).

For each of these we should:

- [ ] Design a maximally complex input CSV (i.e. every cell has a unique value inside it so that we're taxing csvcubed's commands as much as possible.)
- [ ] We should record a memory profile for the application run in an environment which does not constrain the memory that csvcubed can run (i.e. use a VM with way too much memory so csvcubed is never limited in its memory consumption). We should then extract the maxmimum memory consumed by csvcubed during the process and communicate to users that 'a 100,000 row CSV input may need up to X GiB memory for optimal peformance of csvcubed'.
- [ ] We should record how long the process takes and communicate this to the user, e.g. 'a 100,000 row CSV input takes X amount of time'.
- [ ] We should repeat each command at least 5 times in order that we get a sense of the reliable value.

- [ ] This should be written up as a script which a developer can run locally. The above tests should be formally run in an isolated VM for the most reliable results. A developer should be able to control which size of inputs are generated + tested on their local box to avoid wasting their time.

N.B. The script should automatically (randomly) generate the large CSV files so we don't have to move a load of stuff around. The qube-config.json files can be hard coded though.

**Comment by mikeAdamss** [comment]
One thought RE dataset size - I don't think size per se really matters, that'd basically be stress testing pandas which is just down to how much RAM you have.

if I'm understanding things, the structure will be at least as important as the unique values within the columns as its what we leverage for validation, so these two scenarios:

- A "year" column with one thousand entries all of "2022"
- A "year"column with one thousand unique entries spanning the years 1022-2022.

Are likely to require different amounts of resource.

I would consider (a) dynamically creating a handful of example datasets from simple structure to uber complex then (b) run them all at increasing increments of size.

I'm guessing (but don't know for sure), that csvcubed will fail at an earlier point/size when using the complex structures.

**Comment by robons** [comment]
So we want to know:

The approximate memory usage (memory necessary) to run datasets of varying sizes through csvcubed so we can give guidance to users as to what's reasonable (or what size VM they need to provision for this to work efficiently with pandas).

So can we consider:

- [ ] 10,000 rows
- [ ] 100,000 rows
- [ ] 1,000,000 rows
- [ ] 1,000,000,000 rows.

Feel free to stop at 1 million if it's just taking too long (hours+).

**Comment by robons** [comment]
For when we get on to the VM testing, these are the VM specs available in a github runner: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
