### ISSUE TITLE
cell_uri_template should not generate a code list (Score: Tolerable)

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#588]
Right now csvcubed attempts to generate a code list when a dimension has a set `cell_uri_template`. This results in notation changes in the concept scheme, and malformed links and prevents publication to PMD.

The current work around is that when using the `cell_uri_template` keyword for a dimension the user also needs to set `"code_list": false`.

Bug scoring:
Impact = 2 (Easy work around, already documented in this ticket)
Likelihood = 2 (Few datasets will be using `cell_uri_templates`, and few users will try to serialise CSV-W this way).
Total = 4 (Result: Tolerable)

**Comment by canwaf** [comment]
Added comments to this effect in canwaf#551

**Comment by robons** [comment]
Closing as work done in #754 should stop building the CSV-W if cell_uri_template is set but code list is not false.
