### ISSUE TITLE
Profile Build + Inspect Commands

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#623]
As a result of #563, we've identified that the csvcubed build and inspect commands aren't able to cope with the size and complexity of data that we're hoping for.

Roughly csvcubed build + inspect commands should be able to handle data sets which have ~5 million rows of data. i.e. the build command for a data set of that size should ideally be processed by csvcubed build within an hour on one of our developer macbooks. The inspect command for a file of this size should ideally take no more than 10 mins to process.

These are aspirational goals rather than hard requirements, so tell me if it's just impossible achieve them.

- [x] You should attach a python profiler and record multiple flamegraphs showing the CPU load and memory utilisation as a function of time.  These flame graphs should display the function that's currently running (and its parent stack) so we can begin to understand which parts of the code base take significant periods of time for a large data set.

The size of data set that you should consider is 10,000 rows - i.e. not trivially small but doesn't take an age to process. You can use the python script generated in #563 to generate a 'maximally complex' CSV of the appropriate size.

- [x] Highlight the key functions which seem to be taking the most time and make recommendations as to how we can improve the performance of csvcubed in line with our stated ambitions/goals for performance.

**Comment by nimshi89** [comment]
The command that generated the most useful (so far) data:
 scalene tests/profiling/profile.py --outfile results.json --reduced-profile --program-path . --html
and
 scalene tests/profiling/profile.py --outfile results.json --profile-only @profile --program-path . --html

**Comment by nimshi89** [comment]
## Build command profiling

![python-2022-11-16T12_23_36Z.svg](https://images.zenhubusercontent.com/6319fe54f14e8fc1876f7b53/85b66675-1d54-4a50-9ff3-ba8ab927227f)

## Inspect command profiling

![python-2022-11-16T13_55_21Z.svg](https://images.zenhubusercontent.com/6319fe54f14e8fc1876f7b53/663e8043-af03-4a50-a9d9-508f46551adb)
