### ISSUE TITLE
Fix issues in "Writing a qube-config.json" documentation

### ISSUE THREAD

**Issue by CharlesRendle** [GSS-Cogs/csvcubed#648]
The plan is to expand upon the "how-to write metatdata" documentation as a whole (see ticket #520) but for the time being, the page we have currently contains a few inaccuracies.

The future view for this document is that it shall be used as a reference rather than a guide. The guide to writing a qube-config should be written from scratch giving a list of examples. In the event a user wants more detail, then this new guide should refer to this reference document.

- [x] Give the current page a thorough glance in its current form to determine where there are inaccuracies comparing with the qube-config json schema.
Some examples already include:
- [x] Measure columns are not defined by `"type": "measure column"`
- [x] Unit columns are not defined by `"type": "unit column"`
- [x] Link to the same page instead of a specific section of the page (Measure and Unit Columns Configuration **->** `values` **->** [Measures and Units]())
- [x] Bits which say things like `TODO Look this up`

Given the person who picks up this ticket will have spent time understanding this page, they are in a good position to provide thoughts towards how the new "writing a qube-config.json Guide" should look/what it should contain. This is the point at which a new ticket should be written including some of these thoughts.
- [ ] Create a new ticket for writing the new guide

**Comment by CharlesRendle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Features-Squad-61b72275ac896c0010a1b00b/issues/GSS-Cogs/csvcubed/648?planning-poker) with Zenhub @nimshi89 @SarahJohnsonONS @NickPapONS @robons

**Comment by canwaf** [comment]
It looks like we got the suggested week format for the week template wrong. It's a documentation only update.

On https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/templates/ the week pattern for both government and non-government years should contain a W as per https://github.com/epimorphics/IntervalServer/blob/8ad6a52f128041734243dee0d1da02f4504d1013/interval-uris.md#common-patterns.

**Comment by SarahJohnsonONS** [comment]
Notes on what to include in the follow-on ticket: https://docs.google.com/document/d/1iIVtNr3-2GYB25C8ZjlBVaSO-X1m0XGMtaoYUpUnbbM/edit
