### ISSUE TITLE
Support generation of code list without cube

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#664]
Potentially a new sub command or something.

@CharlesRendle to speak with @canwaf to figure out the requirements for this ticket.

TODO: Need to decide how we're going to pass this to csvcubed, i.e.

* `csvcubed build --code-list-config code-list.json` this conflicts with the existing `csvcubed build` command, but could be possible - although it might reduce some of the CLI validations that we have.
* `csvcubed codelist build code-list.json` - this wouldn't conflict with the existing commands at all and give you 100% flexibility.

**Comment by canwaf** [comment]
Hey @CharlesRendle, I'm working through this holiday, so hit me up whenever when you want to talk about this.
