### ISSUE TITLE
Support mixedPeriods for refPeriod templates

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#683]
Following #682, users should be able to define a mixed refPeriod column from template which will expand to the correct objects.

qube-config.json:
```json
"Period": {
    "from_template": "mixedPeriods"
}
```

Which allows the column to contain things like
```csv
Period,Observation
government-quarter/2019/1,10
government-quarter/2019/2,9
government-quarter/2019/3,5
government-quarter/2019/4,9
government-year/2019,33
```

**Comment by robons** [comment]
This has already been addressed. Closing issue.
