### ISSUE TITLE
Completing move from pydantic validation

### ISSUE THREAD

**Issue by CharlesRendle** [GSS-Cogs/csvcubed#688]
upon completion of ticket #674 & #675 & #676
First we need to do the switch over from pydantic (stop using pydantic on a cube)

- [x] Remove the pydantic validation package in csvcubed.utils since it won't be needed anymore (and any associated tests).
- [x] Remove the `PydanticModel` base class entirely and any associated tests. Also make sure to remove it from any classes which inherited from it.
- [x] Remove pydantic validation functions from each of the classes where they're explicitly defined.
- [x] Remove the csvcubed-pydantic dependency from the pyproject.toml (you should use poetry to do all of this for you).
- [x] Need to go into the cube class and alter it to be a `ValidatedModel`. Now change the validation function so that it triggers the `ValidatedModel.validate(...)` function instead of the one on `PydanticModel`. 

- [ ] Archive the csvcubed-pydantic repository (fork).

Then we need to rerun the profiler and hopefully see some improvements
Fingers crossed no followup tickets are needed

Warning: This will be the first time that we've actually tested the validation we wrote in previous tickets on all of the models so you may get a significant number of failing behaviour/unit tests.

**Comment by nimshi89** [comment]
```<=========================================>

The results are from a Build command

Starting time <UTC>: 07:58:11.136000      Finishing time <UTC>: 08:00:18.492000
Avarage run time :0:00:25.471200  Total test time :0:02:07.356000

Max CPU Usage % : 23.47

Max Memory Usage % : 46.97

Avarage CPU Usage % : 12.13

Avarage Memory Usage % : 46.66

<=========================================>
Now running inspect command
WARNING: package sun.awt.X11 not in java.desktop
Killing server agent
Processing metrics for inspect command
<=========================================>

The results are from a Inpect command

Starting time <UTC>: 08:00:21.744000      Finishing time <UTC>: 08:05:08.851000
Avarage run time :0:00:57.421400  Total test time :0:04:47.107000

Max CPU Usage % : 31.26

Max Memory Usage % : 49.62

Avarage CPU Usage % : 13.81

Avarage Memory Usage % : 48.21

<=========================================>
(csvcubed-py3.11) bash-3.2$ 
```

Above are the performance results for the new validation system 
previously the performance was: 

```<=========================================>

The results are from a Build command

Starting time <UTC>: 08:37:01.433000      Finishing time <UTC>: 08:42:53.887000
Avarage run time :0:01:10.490800  Total test time :0:05:52.454000

Max CPU Usage % : 42.52

Max Memory Usage % : 53.35

Avarage CPU Usage % : 16.14

Avarage Memory Usage % : 52.15

<=========================================>
Processing metrics for inspect command
<=========================================>

The results are from a Inpect command

Starting time <UTC>: 08:42:58.047000      Finishing time <UTC>: 08:51:22.155000
Avarage run time :0:01:40.821600  Total test time :0:08:24.108000

Max CPU Usage % : 44.01

Max Memory Usage % : 53.93

Avarage CPU Usage % : 16.79

Avarage Memory Usage % : 52.69

<=========================================>
,,,
