### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sazzadur-ons** [GSS-Cogs/csvcubed#694]
The following link is not found, error 404.

https://gss-cogs.github.io/csvcubed-docs/external/guides/shape-data/configuration/qube-config.md/#measure-and-unit-columns-configuration

**Comment by robons** [comment]
@sazzadur-ons Do you recall which page this link was on?

**Comment by robons** [comment]
I believe that this issue has already [been fixed](https://github.com/GSS-Cogs/csvcubed/commit/261d372f2ffe1ef9633a0607b0da6c31f50ee142#diff-08c3299bd22a707c6875709a0f931d07b14b6877e087d621349b8f436b0ce027L55). Thanks for reporting it.
