### ISSUE TITLE
API function to load a pandas dataframe

### ISSUE THREAD

**Issue by CharlesRendle** [GSS-Cogs/csvcubed#701]
Further to the work from ticket #690, we want to develop an API function which gives the user the ability to load the CSV dataset from their CSVW into a pandas dataframe.

This function should also complete the dereferencing of URI identifiers held inside CSV cells so that the dataframe is constructed using their human-readable label equivalents instead of URIs (which contain underscores, hyphens and are usually all lower-case). This applies to dimensions using locally-defined codelists, locally-defined measures and locally-deifned units.

~In the case of measures and units we need to think about how this will work in the pivoted shape when these columns are not "physically" present in the CSV file. (@robons suggests that we don't explicitly display the unit/measure information anywhere in the data frame - we rely on the user having written the information into the CSV column's title in a human-readable way, e.g. the obs val column could have a title like `Length (cm)`).~

We may also want to think about including the optional ability to override the dereferencing which might be useful for a user who doesn't care about a nicely formatted dataframe and/or is loading a large dataset in which the cost of dereferencing to labels is so high that the operation fails.

We're going to assume that work has been done in #703 to provide us with a detailed description of which components each column in the CSV file relate to.

In the post-MVP future, we should also discuss how we could extend panda's dataframe to add functionality such as `df.cube.get_dimensions()` and have it return a new data frame containing only the dimensions (or something like this).

**Comment by robons** [comment]
todo: We should consider adding helper properties/methods to the dataframes we create: https://pandas.pydata.org/pandas-docs/stable/development/extending.html
