### ISSUE TITLE
Generate code list command

### ISSUE THREAD

**Issue by CharlesRendle** [GSS-Cogs/csvcubed#704]
We want to create a new CLI command in csvcubed which builds a code list CSV-W from a codelist-config.json file without needing any associated cube.

The command should work as follows:

```
csvcubed code-list build <some-config-file.json>
``` 

- [x] Support the following flags we have in the csvcubed build command:
  - [x] `--validation-errors-to-file`
  - [x] `--log-level [warn|err|crit|info|debug]`
  - [x] `--fail-when-validation-error / --ignore-validation-errors` (the default should be the same as in the main build command)
  - [x] `--out` 

- [ ] Ensure that validation errors are presented the user in the same way as they are in the build command.
- [ ] Ensure that logging is configured in the same way as in the build command.

- [x] The command should deserialise the codelist-config.json to a NewQbCodeList in a similar way to `columnschema.py` [(ln:136 - 154) ](https://github.com/GSS-Cogs/csvcubed/blob/e2d79ba85acb4c3769ecdda1a607f3e9d0394bcc/src/csvcubed/readers/cubeconfig/v1/columnschema.py#L136-L154). **However** we need to consider adding support for interpreting different versions of the codelist-config, as we do with qube-config.json files. 
- [x] The command should then use the SkosCodeListWriter class to write the CSV-W to the out directory. 
- [x] The command should then say that it's complete in the same way as we do in the regular build command.

- [x] Write unit tests where relevant.
- [x] Write behaviour scenarios to test the end-to-end functionality, including testing all of the different flags/configurations that the command supports.

- [ ] Consider how we could alter the csv-to-csvw GitHub action so it's possible to recognise a codelist config and build a CSV-W out of it without a corresponding CSV input. Write a ticket to get us to do this.

**Comment by canwaf** [comment]
Can you also add the following to both the code list and data set build commands

- [ ] if the build fails a big red warning saying Build failed, files @ /path/to/what/was/gonna/be/output were not updated`

**Comment by robons** [comment]
As part of this ticket, we need to make sure that the documentation is updated. For example https://gss-cogs.github.io/csvcubed-docs/external/guides/configuration/code-list-config/ should make reference to this.

We should probably add a new page to the `Commands` section for the `code-list build` command.

![image.png](https://images.zenhubusercontent.com/60d35dd0922789587fc8922d/660cc85b-a747-4638-b1f0-7991bfee769b)

Follow the pattern already established for other commands.

**Comment by nimshi89** [comment]
The issue has been addressed @canwaf This is the message that will be displayed for the users.

![Screenshot 2023-02-22 at 14.17.32.png](https://images.zenhubusercontent.com/6319fe54f14e8fc1876f7b53/e6c085b9-e65d-445b-b8fe-0962667504d0)

**Comment by canwaf** [comment]
> The issue has been addressed @canwaf This is the message that will be displayed for the users.


Does this do it for both code lists and data sets?

**Comment by nimshi89** [comment]
Yes I think it does. The same message will be displayed for bot a code-list CSV-W and for the cube as well.
