### ISSUE TITLE
Implement inspectors_cache into remaining unit tests

### ISSUE THREAD

**Issue by CharlesRendle** [GSS-Cogs/csvcubed#728]
In ticket #651, we added a unit test helper `inspectors_cache.py`. This script sets up two dictionaries which contain `CsvwRdfManager` and `DataCubeState` objects for any of the cubes which are used in our unit tests.

By doing this, we have considerably sped up the execution of the unit tests. However, this ticket was completed before the the other inspector tickets (#695, #696, #705) which means that the unit tests added in these tickets were not able to take advantage of the inspectors cache helper.

This ticket seeks to go back and change the new unit tests (after (probably) they have been merged into main).

To do this, you must:
- Find all occurrences of a `CsvwRdfManager` being created in unit tests.
(They most likely will come before the `...inspector` object being created too)
-Change the instantiation so that it calls the relevant`get_..._inspector()` function from `inspectors_cache.py`.

- **Note** You will also need to create the function for `get_code_list_inspector()` which has not yet been written but will follow the same logic as `get_data_cube_inspector()`.

**Comment by robons** [comment]
Addressed as part of existing open tickets related to the inspect API work.
