### ISSUE TITLE
[BUG] Themes duplicated 1 time for every keyword when using inspect command

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#739]
**Describe the issue:**
This one is a weird one, but here goes:

It appears that the theme in a data set's inspect will be duplicated in the inspect output for each keyword in a data set. The CSV-W does serialise properly though. Example from CSV-W built using input files at https://github.com/GSS-Cogs/provider-ons-ess/tree/459cb3b69c548fc45ca3545cb34adf4690ed72f4/aged-16-to-64-years-level-3-or-above-qualifications. Full output at https://gss-cogs.github.io/provider-ons-ess/out/aged-16-to-64-years-level-3-or-above-qualifications/aged-16-to-64-years-level-3-or-above-qualifications/aged-16-to-64-years-level-3-or-above-qualifications.csv-metadata.json_inspect_output.txt.

```
        - Themes: 
                -- https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork
                -- https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork
                -- https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork
                -- https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork
                -- https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork
                -- https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork
                -- https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork
        - Keywords: 
                -- levelling-up
                -- subnational
                -- education
                -- qualifications
                -- united-kingdom
                -- mission-6
                -- employment
```

**Reproducible steps / Code example:**
`csvcubed inspect out/aged-16-to-64-years-level-3-or-above-qualifications.csv-metadata.json`

**Error message obtained / Resulting behaviour:**
As above.

**Expected behaviour:**
A 1:1 relationship between themes and themes. Not a 1:1 relationship between themes and keywords.

**Additional Information:**
This one makes me happy because I haven't a single clue HOW this happens. But I experimented by adding new keywords and the repeat of themes just increased.

**Version information + Operating System:**
python 3.10.3, csvcubed 0.2.3, MacOS something or other.

**Comment by robons** [comment]
Sounds like a cross-join in a SPARQL query bringing out more than we'd hoped for.

**Comment by SarahJohnsonONS** [comment]
Attempt at bug triage:

Impact - 2 or 3
Probability - 3 or 4 - seems to happen whenever a theme is included in the qube-config.json (tested with the Eurovision data set), so it depends how often themes are defined.

**Comment by robons** [comment]
Thanks @SarahJohnsonONS - what's the overall assessed bug category resulting from that?

**Comment by SarahJohnsonONS** [comment]
Interestingly, if you define more than one theme, the keywords are now also duplicated:

- Themes: 
                -- https://eurovision.tv/
                -- https://eurovision.tv/
                -- https://eurovision.com/
                -- https://eurovision.com/
                -- https://eurovision.tv/
                -- https://eurovision.com/
                -- https://eurovision.tv/
                -- https://eurovision.com/
- Keywords: 
                -- Song Contest
                -- European Broadcasting Union
                -- Eurovision
                -- European Broadcasting Union
                -- Sweden
                -- Song Contest
                -- Eurovision
                -- Sweden

**Comment by canwaf** [comment]
Very much (https://tenor.com/8zI0.gif), especially with the two theme suggestion.

Though @SarahJohnsonONS, I would say that the impact of this bug is a 1 - "Typographical/functionality quirk which is ignorable".

**Comment by robons** [comment]
There are two approaches we could take to this ticket:

* Truly fix the underlying SPARQL query so it only brings back the distinct results for the themes and the keywords fields (this may involve writing a couple of sub queries).
* Just sticking the themes/keywords into a set to get the distinct values after the SPARQL query has been executed (this is the less-favourable option if the first one introduces way too many problems).

Try to take the first approach, but the second approach is always there if we need it. 

- [ ] Write a unit test with a test-case containing multiple themes and keywords and make sure the API only brings back the unique results there-in.

**Comment by robons** [comment]
There are two approaches we could take to this ticket:

* Truly fix the underlying SPARQL query so it only brings back the distinct results for the themes and the keywords fields (this may involve writing a couple of sub queries).
* Just sticking the themes/keywords into a set to get the distinct values after the SPARQL query has been executed (this is the less-favourable option if the first one introduces way too many problems).

Try to take the first approach, but the second approach is always there if we need it. 

- [ ] Write a unit test with a test-case containing multiple themes and keywords and make sure the API only brings back the unique results there-in.
