### ISSUE TITLE
Add Local Attribute/Unit Code-List definitions to QB DataStructureDefinition

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#74]
When a user defines a local measure, it is automatically serialised as JSON-LD and inserted into the CSV-W metadata's JSON file. This is because each measure must have its own `qb:MeasureComponentSpecification` defined in the `qb:DataStructureDefinition`. Unfortunately, unlike measures, attributes & units aren't defined in the dataset's *DataStructureDefinition*. As a result we aren't currently serialising them into the CSV-W so units are referenced without being defined.

## Task

Any instance of `NewQbAttribute` should ensure that when its [qb:AttributeComponentSpecification](https://github.com/GSS-Cogs/csvwlib/blob/f8ceefd7fcf1d97cfa6dc0da235253fbcd0aa701/sharedmodels/sharedmodels/rdf/qb.py#L124) is created, we link it to a new `skos:ConceptScheme` which defines all of the URIs which we intend to use with this attribute.

Similarly, any instance of a `NewQbUnit` should ensure that when the corresponding `sdmx-attribute:unit`'s *AttributeComponentSpecification* is defined, it ensures that the new unit is defined in a new `skos:ConceptScheme` linked to by the *AttributeComponentSpecification*.

Attributes don't necessarily have to point to URI values and can instead point at literal values. We don't currently use this functionality, however we should still support users who want to do this. **Create a new subclass of `QbAttribute` called `NewQbAttributeLiteral` which allows us to define a new attribute which is designed to point at literal values.** Note that the corresponding `qb:AttributeComponentSpecification` does *not* need a code-list attached in this situation.

Related issues #79, #80.

**Comment by robons** [comment]
todo: @robons to chat with @ajtucker about this to see whether we want to use codelists with attribute values/units.

**Comment by Robsteranium** [comment]
We've [discussed this today](https://onswebsite.slack.com/archives/CNA5LRUUT/p1636969933193700) and agreed we're happy requiring attributes to be coded. This will help when constructing observations and their reference data. Those with literal values won't be coded and should distinguish themselves as `owl:DatatypeProperty`s. See Swirrl/pmd-rdf-validations#8 for more details on the proposed validation.
