### ISSUE TITLE
[BUG]Investigate why the schema validation errors are not handled properly

### ISSUE THREAD

**Issue by nimshi89** [GSS-Cogs/csvcubed#745]
After a brief investigation into the #714 the warnings that has been expected has not been displayed, then further changes has been made that should have triggered a validation error, but the cubed was build and no error was flagged. Possible that the Schema validations are not handled properly due to some changed that has been made recently.

**Comment by nimshi89** [comment]
Bug Triage

-  Impact = 4(High) The issue will not raise Schema validation error which should not allow cubed to be constructed, but due to the BUG the invalid cubes can. be made(without the user being aware of the error/errors). 
- Probability = 5(High) This could affect a large portion of the users
-Combined Score = 20 (Critical BUG)

**Comment by robons** [comment]
Closing as this issue never really exists.
