### ISSUE TITLE
Restrict configuration of cell_uri_template for dimensions

### ISSUE THREAD

**Issue by SarahJohnsonONS** [GSS-Cogs/csvcubed#754]
If `cell_uri_template` is defined for a dimension in a qube-config.json file, this should require the user to define either a `from_existing` property *or* set `code_list` as `false`.

- [x] Update the JSON Schema so that when you have `cell_uri_template` set, it highlights where you have failed to set `from_existing` *OR* where `code_list` is not `false`.  The way you can achieve this is by creating two dimension types (from the existing one that we have). The first one should not have `cell_uri_template` on it at all, and the second one should have:
    - [x] `cell_uri_template` is able to be set
    - [x] The only valid value for `code_list` should be a constant value of `false` in this type definition.
    - [x] This type needs a `required` restriction saying that *either* `from_existing` is set *OR* `code_list` is set (in which case the value must be `false` according to the type definition).

If you take  the above approach, it will not be possible to set the `cell_uri_template` without getting a warning from vscode/the JSON schema validation stuff in the csvcubed build command.

- [ ] Add a validation error which gives the user an error when they have defined a dimension which doesn't use `from_existing` or have `code_list: false`. This will require a new documentation page, PURL URI for the validation error, etc. as is standard for all validation errors.
- [ ] Add a unit test to ensure this validation errors occurs in the setup described.

**Comment by MuazzamChaud** [comment]
{
    // When reusing an existing dimension which either has a code-list or doesn't have a code list (we 
    //don't care)
    "from_existing": "http://example.com/dimensions/some_dimension",
    "cell_uri_template": "http://example.com/code-lists/the-corresponding/code-list/{+column_name}"
}

{
    // In this case we don't want any code list for our newly defined dimension, we just point at a bunch 
    //of URIs.
    "code_list": false,
    "cell_uri_template": "http://reference.data.gov.uk/id/year/{+column_name}"
}

{
    // todo: Reconcile this with the ticket atm.
    // In this example we have a bunch of concepts already defined and we want csvcubed to create a 
    //code list for us from the unique values.
    // I don't think we support this atm.
    "code_list": true,
    "cell_uri_template": "http://reference.data.gov.uk/id/year/{+column_name}"
}

{
    // default: "code_list": true
    "cell_uri_template": "http://reference.data.gov.uk/id/year/{+column_name}"
}

The bottom two examples are not supported atm and we’re going to try to approach this ticket differently, by trying to support all of the above examples. We want to make changes in files such as codelist.py and columnchema.py, where newDimentions and existingDimentions are defined, where codelist are generated for these dimentions.

**Comment by SarahJohnsonONS** [comment]
(From the mind of @robons):

We need to define the behaviour where the user defined both the `cell_uri_template` and sets the `code_list` to be a code-list-config.json definition of what a code list is (i.e. either an in-line definition, or defined in a separate JSON file).

I think in this case, seeing as the user already had the option to set the `same_as` relationships against the concepts in their code list, the introduction of `cell_uri_template` gives us conflicting instructions. We should raise an exception in this case and stop what we're doing. We need to provide an error documentation page explaining to the user why we're not letting them do this and what they likely want to do instead.
