### ISSUE TITLE
BUG - Misleading error message when no attribute values present

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#760]
If you define a cube with an obs status column reusing the observation-status template, but your dataset doesn't actually have any values in that column, then you end up with the following error:

```bash
$ csvcubed build 4g-coverage.csv --config qube_config_template.json 
2023-03-09 14:14:50,226 - csvcubed.utils.cli - ERROR - Validation Error: The 'Observation Status' column definition is missing a 'cell_uri_template'; a suitable value could not be inferred. (cli.py:67)
2023-03-09 14:14:50,227 - csvcubed.utils.cli - ERROR - More information: http://purl.org/csv-cubed/err/csv-col-uri-temp-mis (cli.py:69)
```

This is as a result of the code [here](https://github.com/GSS-Cogs/csvcubed/blob/24106abeebf8a94b4ee5dea498630050f887f753/src/csvcubed/utils/qb/validation/cube.py#L71). 

This isn't exactly 100% the right error in all circumstances.

Example inputs:  [https://app.zenhub.com/files/374709947/d5f592fd-a23c-46e4-a858-b0dc9a016971/download](https://app.zenhub.com/files/374709947/d5f592fd-a23c-46e4-a858-b0dc9a016971/download)

Waiting on @canwaf to confirm whether the proposed work-around works.

------

- [x] Alter the error message so that it presents a comprehensible message to the user explaining that they've got an attribute values column that isn't required/doesn't have any values in it.
- [x] Write a unit test which ensures this validation error is generated in the aforementioned test case.
- [x] Ensure there's a PURL link and documentation page for this new kind of validation error (And make sure to update the gsheets copy of the redirects)

**Comment by canwaf** [comment]
What's the workaround?

**Comment by robons** [comment]
Sorry, it didn't work.
