### ISSUE TITLE
AP - Investigate using `skos:ConceptSchemes` to hold/define attribute values against attribute resources

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#794]
https://github.com/GSS-Cogs/application-profile#attribute

We want to use code lists to hold the attribute values it's possible to use in an attribute's column within a data cube. i.e. Attibutes will have code lists now just like dimensions do.

This ticket is to scope out the alterations which will need to be made to csvcubed (and its documentation) in order to support this.

## To Consider

- How does it affect the qube-config.json structure? Do we need a new minor/major version of it? How do we need to alter the JSON schema so that we represent code lists against Resource Attributes in the same (or similar) way to how we do it against dimensions?
- How does this affect the readers which read in from qube-config.json files?
- Do we need to support backwards compatibility here? Is this a major version of the qube-config.json or is it a minor version change?
- How does this affect validation? We should probably be doing similar validations to the ones applied to dimension's code lists.
- How do we need to alter the QbWriter/SkosCodeListWriter code to output cubes with code lists for attribute resources?
- How does this impact the InspectAPI - what do we need to change? And can we do backwards-compatible changes so the InspectAPI can support both the old way of defining attribute values and the new code list way?
- How does the external user documentation need to change?

## What has been Considered
- In the qwiter there is already some functionality developed and can be used/altered for this ticket.
- Investigate how the changes could be made
- Create a "prototype" and see what issues/technical difficulties turn up 
- Add to the ticket what changes need to be made with possible solution suggestions
- Consider if the new functionalities can be added as optional functionality

**Comment by nimshi89** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Features-Squad-61b72275ac896c0010a1b00b/issues/GSS-Cogs/csvcubed/794?planning-poker) with Zenhub @CharlesRendle @NickPapONS @SarahJohnsonONS @nimshi89
