### ISSUE TITLE
CSV-W Profile - CSV-Ws generated by csvcubed should contain dcat:Distributions not dcat:Datasets

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#826]
If the CSV-W is just a distribution of a dcat:Dataset then we shouldn't be defining the dcat:Dataset inside it. The dcat:Dataset and all other catalogue metadata should be defined and maintained by the application server, not individual CSV-Ws before they've been uploaded to that wider world.

**Comment by rossbowen** [comment]
Think we've discussed this and I've made the case for the `dcat:Dataset` being part of the CSVW, my primary rationale being that I think an analyst using `csvcubed` would find it convenient to define the CSV distribution and the `dcat:Dataset` at the same time.

We spoke today about whether then, through using `csvcubed` the analyst should be able to add triples to the CSVW like:

```jsonc
{
    // ...
    "@id": "http://example.org/dataset",
    "@type": "dcat:Dataset",
    "dcat:distribution": [
        {
            "@id": "http://example.org/dataset.xlsx",
            "@type": "dcat:Distribution",
            "dcat:mediaType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        }
    ]
  // ...
}
```

and while I don't think there shouldn't be anything stopping them if they wanted to add those triples, I think that sort of information could be added outside of the CSVW, and it's not a big priority for the user to be able to add this right now. So if `csvcubed` can't do it right now, I don't think it's a dealbreaker.

I've transferred to `csvcubed` repo and will close.
